### ISSUE TITLE
Bug with readable-stream?

### ISSUE THREAD

**Issue by msceliot** [blockchain/service-my-wallet-v3#11]
Hi,
I have installed service-my-wallet-v3 on CentOs. When I start it and call the API, the first call works well with this output:
```
[ReferenceError: navigator is not defined]
[ReferenceError: window is not defined]
Transaction.prototype.sign is deprecated.  Use TransactionBuilder instead.
Transaction.prototype.signInput is deprecated.  Use TransactionBuilder instead.
published
```
But for the second call I get this output and the server is terminated:
```
/usr/lib/node_modules/service-my-wallet-v3/node_modules/readable-stream/lib/_stream_writable.js:202
    encoding = state.defaultEncoding;
                    ^
TypeError: Cannot read property 'defaultEncoding' of undefined
    at DuplexWrapper.Writable.write (/usr/lib/node_modules/service-my-wallet-v3/node_modules/readable-stream/lib/_stream_writable.js:202:21)
    at DuplexWrapper.Writable.end (/usr/lib/node_modules/service-my-wallet-v3/node_modules/readable-stream/lib/_stream_writable.js:426:10)
    at API.request (/usr/lib/node_modules/service-my-wallet-v3/node_modules/blockchain-wallet-client/src/api.js:91:30)
    at API.retry (/usr/lib/node_modules/service-my-wallet-v3/node_modules/blockchain-wallet-client/src/api.js:118:12)
    at API.getHistory (/usr/lib/node_modules/service-my-wallet-v3/node_modules/blockchain-wallet-client/src/api.js:207:15)
    at Wallet.getHistory (/usr/lib/node_modules/service-my-wallet-v3/node_modules/blockchain-wallet-client/src/blockchain-wallet.js:391:21)
    at WebSocket.onMessage (/usr/lib/node_modules/service-my-wallet-v3/node_modules/blockchain-wallet-client/src/wallet.js:236:23)
    at WebSocket.emit (events.js:98:17)
    at Receiver.ontext (/usr/lib/node_modules/service-my-wallet-v3/node_modules/ws/lib/WebSocket.js:816:10)
    at /usr/lib/node_modules/service-my-wallet-v3/node_modules/ws/lib/Receiver.js:477:18
    at /usr/lib/node_modules/service-my-wallet-v3/node_modules/ws/lib/Receiver.js:361:7
    at /usr/lib/node_modules/service-my-wallet-v3/node_modules/ws/lib/PerMessageDeflate.js:238:5
    at afterWrite (_stream_writable.js:278:3)
    at onwrite (_stream_writable.js:270:7)
    at WritableState.onwrite (_stream_writable.js:97:5)
    at afterTransform (_stream_transform.js:99:5)
```
I this a bug or I should do something?

**Comment by jtormey** [comment]
For some reason, `this._writableStream` was not defined in a call to `Writable.prototype.end`, so when trying to get the default encoding the program would crash. This has been fixed in patch v3.3.3 of the my-wallet-v3 module by explicitly setting the encoding when ending streams. Thanks for reporting the issue, let me know if you have anymore problems.
