### ISSUE TITLE
Unable to start  blockchain-wallet-service

### ISSUE THREAD

**Issue by NickLD** [blockchain/service-my-wallet-v3#113]
Running: service: 0.21.3, Node v5.11.1

I can't get the service to run. Here is the log:
```

 sudo blockchain-wallet-service start --port 3000
1464136579094 - error:  Error: Cannot find module 'es6-promise'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/blockchain-wallet-service/node_modules/blockchain-wallet-client-prebuilt/index.js:3:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/blockchain-wallet-service/src/create.js:6:21)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
1464136579099 - error:  TypeError: Cannot read property 'start' of undefined
    at start (/usr/lib/node_modules/blockchain-wallet-service/bin/cli.js:50:9)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)

```

I then NPM installed es6-promise and ran it with the same output.

Any Idea on whats happening?

**Comment by NickLD** [comment]
I fixed the issue. I had to install the es6-promise as a global module along with the others it needed so it would find and start them.
