### ISSUE TITLE
Can't start Service

### ISSUE THREAD

**Issue by edgar017** [blockchain/service-my-wallet-v3#120]
Please include your service-my-wallet-v3 and NodeJS version numbers when submitting an issue.
Example: *Service v0.18.0, Node v0.12.5*

Service: 0.21.4, Node v0.10.25

1465351220310 - error:  TypeError: Object prototype may only be an Object or null
    at Function.create (native)
    at Object.exports.inherits (util.js:555:27)
    at Object.<anonymous> (/usr/local/lib/node_modules/blockchain-wallet-service/node_modules/blockchain-wallet-client-prebuilt/src/payment.js:84:6)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/blockchain-wallet-service/node_modules/blockchain-wallet-client-prebuilt/index.js:28:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
1465351220316 - error:  TypeError: Cannot call method 'start' of undefined
    at start (/usr/local/lib/node_modules/blockchain-wallet-service/bin/cli.js:50:10)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
root@Nodo-01-Ether:~# Cannot call method 'start' of undefined

**Comment by derrend** [comment]
I had this problem.
Installation guide states "node >= 0.12.0"
I fixed it by upgrading my nodejs version by following the instructions here:
http://askubuntu.com/questions/594656/how-to-install-the-latest-versions-of-nodejs-and-npm-for-ubuntu-14-04-lts

**Comment by jtormey** [comment]
Yes, the issue is your node version. See #14.
Thanks for the link @derrend, I'll put that in the docs in case anyone else runs into this.
