### ISSUE TITLE
installation error 

### ISSUE THREAD

**Issue by arthurkmaster** [blockchain/service-my-wallet-v3#181]
Please include your service-my-wallet-v3 and NodeJS version numbers when submitting an issue.
Example: *Service v0.18.0, Node v0.12.5*

couldn't start the service after the installation.  error in missing one module.  any help ?  
Service v0.22.4, Node v4.2.6

-------------------
blockchain-wallet-service start -p 3000

1488364188622 - error:  Error: Cannot find module 'es6-promise'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/blockchain-wallet-service/node_modules/blockchain-wallet-client-prebuilt/index.js:3:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
1488364188627 - error:  TypeError: Cannot read property 'start' of undefined
    at start (/usr/local/lib/node_modules/blockchain-wallet-service/bin/cli.js:50:9)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)

**Comment by jtormey** [comment]
What version of npm are you using?

**Comment by robertyun** [comment]
i got same issue and install each required module
npm install -g [module-name]
ex) npm install -g es6-promise

npm version 3.10.10

**Comment by robertyun** [comment]
i guess you need install npm install -g java if you dont have on your system
first install java (below for centos)
https://tecadmin.net/install-java-8-on-centos-rhel-and-fedora/ 
and npm install -g java
and npm install -g blockchain-wallet-service

**Comment by jtormey** [comment]
Seems strange that not having Java would cause other dependencies to fail to install. Will look into it.

**Comment by ac-dc** [comment]
I have exactly the same issue
npm 3.8.6
node.js 6.0.0

> bufferutil@1.2.1 install C:\Users\user\AppData\Roaming\npm\node_modules\blockchain-wallet-service\node_modules\bufferutil
> node-gyp rebuild


C:\Users\user\AppData\Roaming\npm\node_modules\blockchain-wallet-service\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(54,5): error MSB8020: The build tools for Visual Studio 2012 (Platform Toolset = 'v110') cannot be found. To build using the v110 build tools, please install Visual Studio 2012 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [C:\Users\user\AppData\Roaming\npm\node_modules\blockchain-wallet-service\node_modules\bufferutil\build\bufferutil.vcxproj]
gyp ERR! build error
