### ISSUE TITLE
Faulty Login to Blockchain Service

### ISSUE THREAD

**Issue by codethejason** [blockchain/service-my-wallet-v3#192]
When I try running the blockchain service and doing a login call, it successfully returns the information in an array but then produces an error immediately after, shutting down the localhost process. I'm running node v5.12 and blockchain service v0.16

```root@CryptoBE:~# blockchain-wallet-service start --port 3000
blockchain.info wallet service v0.16.0 running on 127.0.0.1:3000
Server Time offset -49416ms - This offset -49416
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: unexpected server response (503)
    at ClientRequest.response (/usr/local/lib/node_modules/blockchain-wallet-service/node_modules/blockchain-wallet-client-prebuilt/node_modules/ws/lib/WebSocket.js:694:15)
    at ClientRequest.g (events.js:273:16)
    at emitOne (events.js:90:13)
    at ClientRequest.emit (events.js:182:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:469:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)
    at TLSSocket.socketOnData (_http_client.js:359:20)
    at emitOne (events.js:90:13)
    at TLSSocket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at TLSSocket.Readable.push (_stream_readable.js:111:10)
    at TLSWrap.onread (net.js:534:20)
```

**Comment by jtormey** [comment]
I believe this error was fixed, could you try using the latest version?

**Comment by codethejason** [comment]
Alright, but how come npm 3.8.6 does not work with `npm update -g blockchain-wallet-service`?

**Comment by jtormey** [comment]
One of our dependencies doesn't install correctly on npm 3. We're in the process of making it optional, so that installing with npm 3 is ok.

You get that error after installing with npm 2? Were there any errors during the actual install?

**Comment by codethejason** [comment]
Thank you, everything's working as intended now.

**Comment by Duanthse03268** [comment]
"You might need Java while installing (see here). A dependency (the same one that won't work on npm 3) needs it, this requirement will be dropped soon.". I'm using window server installed JDK but still got error  **error: Error decrypting wallet, please check that your password is correct**
