### ISSUE TITLE
TypeError: Object �|Z���K�ս��r0��̔X��5��8H`� has no method 'compare'

### ISSUE THREAD

**Issue by sparkwj** [blockchain/service-my-wallet-v3#21]
after login, when i call the balance api, i got this error.

myserver# blockchain-wallet-service start -p 3000
blockchain.info wallet service running on 127.0.0.1:3000
Server Time offset -10359.25ms - This offset -10359.25
Server Time offset -10361.125ms - This offset -10363

TypeError: Object �|Z���K�ս��r0��̔X��5��8H`� has no method 'compare'
    at validatePassword (/usr/lib/node_modules/service-my-wallet-v3/src/wallet-cache.js:33:64)
    at WalletCache.getWallet (/usr/lib/node_modules/service-my-wallet-v3/src/wallet-cache.js:57:17)
    at WalletCache.login (/usr/lib/node_modules/service-my-wallet-v3/src/wallet-cache.js:47:8)
    at MerchantAPI.login (/usr/lib/node_modules/service-my-wallet-v3/src/api.js:11:16)
    at /usr/lib/node_modules/service-my-wallet-v3/src/server.js:96:32
    at Layer.handle [as handle_request] (/usr/lib/node_modules/service-my-wallet-v3/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/lib/node_modules/service-my-wallet-v3/node_modules/express/lib/router/route.js:131:13)
    at /usr/lib/node_modules/service-my-wallet-v3/src/server.js:109:5
    at Layer.handle [as handle_request] (/usr/lib/node_modules/service-my-wallet-v3/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/lib/node_modules/service-my-wallet-v3/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/usr/lib/node_modules/service-my-wallet-v3/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/service-my-wallet-v3/node_modules/express/lib/router/layer.js:95:5)
    at /usr/lib/node_modules/service-my-wallet-v3/node_modules/express/lib/router/index.js:277:22
    at param (/usr/lib/node_modules/service-my-wallet-v3/node_modules/express/lib/router/index.js:349:14)
    at param (/usr/lib/node_modules/service-my-wallet-v3/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/usr/lib/node_modules/service-my-wallet-v3/node_modules/express/lib/router/index.js:410:3)

**Comment by sparkwj** [comment]
oh, i found the closed issue.

**Comment by shawnblue** [comment]
What was the solution?

**Comment by jtormey** [comment]
Upgrading to a newer version of node ( >= 0.12.0 ). See #14

**Comment by shawnblue** [comment]
Thanks
