### ISSUE TITLE
Unable to send bitcoin

### ISSUE THREAD

**Issue by yaswanth-rails** [blockchain/service-my-wallet-v3#222]
service-my-wallet-v3: 0.24.0
nodejs: 6.10.3 npm: 3.10.10

I am unable to send bitcoins, getting  "address.balance must be a positive number", but I have enough balance to send. Please check below logs.

1495026295337 - error: undefined Error: address.balance must be a positive number
    at Address.set (/usr/lib/node_modules/blockchain-wallet-service/node_modules/blockchain-wallet-client-prebuilt/src/address.js:76:15)
    at Wallet.updateAccountAndAddressesInfo (/usr/lib/node_modules/blockchain-wallet-service/node_modules/blockchain-wallet-client-prebuilt/src/blockchain-wallet.js:358:23)
    at Array.forEach (native)
    at Wallet._updateWalletInfo (/usr/lib/node_modules/blockchain-wallet-service/node_modules/blockchain-wallet-client-prebuilt/src/blockchain-wallet.js:364:17)
    at process._tickCallback (internal/process/next_tick.js:109:7)

Please help me to solve this error, Thank You.

**Comment by jtormey** [comment]
This is caused by a double spend in the network, it should resolve itself after a few days.
