### ISSUE TITLE
Unable to start block chain wallet service in windows 7 -- Still no luck

### ISSUE THREAD

**Issue by vempatisuresh** [blockchain/service-my-wallet-v3#226]
I tired to setup block chain wallet service to build a payment serive. With lot of issues, I have resolved one by one issue to install block chain wallet service. Finally i have installed block chain wallet service in my local system.

nods js - 7.10.0 and npm - 2.15.12 version in my windows environment.

But when i am trying to start the block chain wallet service i am getting the below error:

C:\Users\sv185062>blockchain-wallet-service start --port 3000
1495703972856 - error:  Error: Cannot find module 'bip39'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\sv185062\AppData\Roaming\npm\node_modules\bl
ockchain-wallet-service\src\create.js:4:13)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\sv185062\AppData\Roaming\npm\node_modules\bl
ockchain-wallet-service\src\wallet-cache.js:13:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
1495703973105 - error:  TypeError: Cannot read property 'start' of undefined
    at start (C:\Users\sv185062\AppData\Roaming\npm\node_modules\blockchain-wall
et-service\bin\cli.js:56:9)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)

Tried all possibilities but no luck. 

Any help would be  appreciated!!!

**Comment by jtormey** [comment]
What version of npm are you using, this kind of error is common with npm 3. Could you try installing with npm 2 to see if that works?

**Comment by jtormey** [comment]
Sorry, this was actually an issue with a missing dependency in v0.25.0, it's been fixed in v0.25.1. Upgrading should solve your issue.
