### ISSUE TITLE
Unable to start blockchai service

### ISSUE THREAD

**Issue by SavinoSchiavone** [blockchain/service-my-wallet-v3#236]
Please include your service-my-wallet-v3 and NodeJS version numbers when submitting an issue.
Example: *Service v0.18.0, Node v0.12.5*

Nodejs version: v6.10.3
npm version: 3.10.10
Service: 0.25.2 (latest)

Command: blockchain-wallet-service start --port 3000

Error:

blockchain-wallet-service start --port 3000
1496766130685 - error:  Error: Cannot find module 'es6-promise'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/blockchain-wallet-service/node_modules/blockchain-wallet-client-prebuilt/index.js:3:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/blockchain-wallet-service/src/create.js:11:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
1496766130725 - error:  TypeError: Cannot read property 'start' of undefined
    at start (/usr/local/lib/node_modules/blockchain-wallet-service/bin/cli.js:58:9)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)

Please help me. I'm using Ubuntu 16.04

**Comment by SavinoSchiavone** [comment]
UPDATE: 
Now I've got npm 2.15.12 and I've got another error:


1496767772600 - error:  Error: Cannot find module 'isomorphic-fetch'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/blockchain-wallet-service/node_modules/blockchain-wallet-client-prebuilt/index.js:4:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/blockchain-wallet-service/src/create.js:11:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
1496767772624 - error:  TypeError: Cannot read property 'start' of undefined
    at start (/usr/local/lib/node_modules/blockchain-wallet-service/bin/cli.js:58:9)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)

**Comment by SavinoSchiavone** [comment]
UPDATE:
I've done this command: npm install -g isomorphic-fetch
and after I've got "Cannot find module 'sjcl'
and I've done: npm install -g sjcl
and now it seems working:

1496767933089 - info: blockchain.info wallet service v0.25.2 running on http://127.0.0.1:3000
