### ISSUE TITLE
blockchain-wallet-service start errors

### ISSUE THREAD

**Issue by senaweb** [blockchain/service-my-wallet-v3#238]
Service v0.26.0, Node v6.11.0

I am getting the error bellow whiles trying to start the service with the command "blockchain-wallet-service start --port 3000"

1497261948044 - error:  Error: Cannot find module 'core-js/modules/es6.symbol'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/blockchain-wallet-service/node_modules/blockchain-wallet-client/lib/index.js:6:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/blockchain-wallet-service/src/create.js:11:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
1497261948121 - error:  TypeError: Cannot read property 'start' of undefined
    at start (/usr/local/lib/node_modules/blockchain-wallet-service/bin/cli.js:58:9)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)

Is there something I did not do well (new to this though), what could be the solution to this?

**Comment by jtormey** [comment]
Try upgrading to npm 3, then installing. `npm install -g npm@3`

**Comment by potadibyo** [comment]
after installing npm install -g npm@3 still blockchain-wallet-service start --port 3000 still gives error.. help me

**Comment by KrotovRoman** [comment]
At me too at start there are errors!

`blockchain-wallet-service start --port 3000
1504807033730 - error: Error: Cannot find module 'core-js/modules/es6.symbol'
at Function.Module._resolveFilename (module.js:338:15)
at Function.Module._load (module.js:280:25)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object.<anonymous> (/usr/local/lib/node_modules/blockchain-wallet-service/node_modules/blockchain-wallet-client/lib/index.js:6:1)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object.<anonymous> (/usr/local/lib/node_modules/blockchain-wallet-service/src/create.js:11:18)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
1504807033777 - error: TypeError: Cannot call method 'start' of undefined
at start (/usr/local/lib/node_modules/blockchain-wallet-service/bin/cli.js:58:10)
at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)`

What to do?

**Comment by abispo** [comment]
I'm facing the same problem.

`1528122484943 - error:  SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/blockchain-wallet-service/node_modules/bitcoin-sfox-client/node_modules/bitcoin-exchange-client/index.js:2:13)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/blockchain-wallet-service/node_modules/bitcoin-sfox-client/lib/sfox.js:39:16)
    at Module._compile (module.js:410:26)
1528122484957 - error:  TypeError: Cannot read property 'start' of undefined
    at start (/usr/local/lib/node_modules/blockchain-wallet-service/bin/cli.js:58:9)
    at Timer.listOnTimeout (timers.js:92:15)`

npm version is 3.5.2 and nodejs version is 4.2.6.
