### ISSUE TITLE
ubuntu installation error

### ISSUE THREAD

**Issue by bigup401** [blockchain/service-my-wallet-v3#239]
Please include your service-my-wallet-v3 and NodeJS version numbers when submitting an issue.
Example: *Service v0.18.0, Node v0.12.5*

am getting this error after installation 

blockchain-wallet-service start --port 3030 1497723591039 - error: Error: Unsupported crypto version at Object.<anonymous> (/usr/local/lib/node_modules/blockchain-wallet-service/node_modules/bip39/node_modules/pbkdf2/index.js:4:9) at Module._compile (module.js:456:26) at Object.Module._extensions..js (module.js:474:10) at Module.load (module.js:356:32) at Function.Module._load (module.js:312:12) at Module.require (module.js:364:17) at require (module.js:380:17) at Object.<anonymous> (/usr/local/lib/node_modules/blockchain-wallet-service/node_modules/bip39/index.js:3:14) at Module._compile (module.js:456:26) at Object.Module._extensions..js (module.js:474:10) at Module.load (module.js:356:32) at Function.Module._load (module.js:312:12) at Module.require (module.js:364:17) at require (module.js:380:17) at Object.<anonymous> (/usr/local/lib/node_modules/blockchain-wallet-service/src/create.js:4:13) at Module._compile (module.js:456:26) 1497723591054 - error: TypeError: Cannot call method 'start' of undefined at start (/usr/local/lib/node_modules/blockchain-wallet-service/bin/cli.js:58:10) at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)

**Comment by jtormey** [comment]
It sounds like you're using an outdated version of node. Try using version 6 or later.
