### ISSUE TITLE
Crashes and lockup when blockchain.info returns a 522

### ISSUE THREAD

**Issue by johan-karlsson-goobit-se** [blockchain/service-my-wallet-v3#24]
Hello,

we use the blockchain API to provide wallets for our customers on our exchange service, so we are running a fairly busy node. We have found some issues with random crashes, and also a lock issue when blockchain.info returns a 522 error.

We are running version 0.12, and have altered the cli.js file to make the application compatible with the forever node module (provides automatic restart after a crash), and also to add improved logging.

Please see the attached log below

```
[2016-01-07 00:52:11] Server Time offset 63.875ms - This offset 96
[2016-01-07 01:32:32] Server Time offset 24.75ms - This offset 24.75
[2016-01-07 01:32:32] Server Time offset 47.875ms - This offset 71
[2016-01-07 01:42:22] Server Time offset 23ms - This offset 23
[2016-01-07 01:42:22] Server Time offset 46.5ms - This offset 70
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: unexpected server response (521)
    at ClientRequest.response (/usr/lib/node_modules/blockchain-wallet-service/node_modules/blockchain-wallet-client-prebuilt/node_modules/ws/lib/WebSocket.js:694:15)
    at ClientRequest.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:415:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
    at TLSSocket.socketOnData (_http_client.js:305:20)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at TLSSocket.Readable.push (_stream_readable.js:110:10)
    at TLSWrap.onread (net.js:523:20)
error: Forever detected script exited with code: 1
error: Script restart attempt #1
[2016-01-07 01:56:20] blockchain.info wallet service running on 127.0.0.1:3000
[2016-01-07 07:25:27] Server Time offset 36.75ms - This offset 36.75
[2016-01-07 07:25:27] Server Time offset 60.375ms - This offset 84
[2016-01-07 09:12:53] Server Time offset 24.75ms - This offset 24.75
[2016-01-07 09:12:54] Server Time offset 25.375ms - This offset 26

(parts of the log removed to increase readability)

[2016-01-14 09:48:11] Server Time offset 69.125ms - This offset 91.75
[2016-01-14 09:48:11] Server Time offset 81.3125ms - This offset 93.75
[2016-01-14 10:13:49] Server Time offset 51.75ms - This offset 51.75
[2016-01-14 10:13:49] Server Time offset 39.375ms - This offset 27
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: zlib binding closed
    at DeflateRaw.Zlib._transform (zlib.js:484:15)
    at DeflateRaw.Transform._read (_stream_transform.js:167:10)
    at DeflateRaw.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:292:12)
    at clearBuffer (_stream_writable.js:396:7)
    at onwrite (_stream_writable.js:331:7)
    at WritableState.onwrite (_stream_writable.js:89:5)
    at afterTransform (_stream_transform.js:79:5)
    at TransformState.afterTransform (_stream_transform.js:54:12)
    at Zlib.callback (zlib.js:613:5)
error: Forever detected script exited with code: 1
error: Script restart attempt #2
[2016-01-14 10:44:58] blockchain.info wallet service running on 127.0.0.1:3000
[2016-01-14 10:55:44] Server Time offset 39.5ms - This offset 39.5
[2016-01-14 10:55:45] Server Time offset 32.125ms - This offset 24.75
[2016-01-14 11:32:58] Server Time offset 27.75ms - This offset 27.75

(parts of the log removed to increase readability)

[2016-01-15 21:58:55] Server Time offset 39.75ms - This offset 39.75
[2016-01-15 21:58:56] Server Time offset 81.375ms - This offset 123
[2016-01-16 05:46:34] Server Time offset 28.75ms - This offset 28.75
[2016-01-16 05:46:34] Server Time offset 26.875ms - This offset 25
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: unexpected server response (522)
    at ClientRequest.response (/usr/lib/node_modules/blockchain-wallet-service/node_modules/blockchain-wallet-client-prebuilt/node_modules/ws/lib/WebSocket.js:694:15)
    at ClientRequest.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:415:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
    at TLSSocket.socketOnData (_http_client.js:305:20)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at TLSSocket.Readable.push (_stream_readable.js:110:10)
    at TLSWrap.onread (net.js:523:20)
error: Forever detected script exited with code: 1
error: Script restart attempt #3
[2016-01-16 08:06:02] blockchain.info wallet service running on 127.0.0.1:3000
[2016-01-16 09:04:29] Server Time offset 40.75ms - This offset 40.75
[2016-01-16 09:04:29] Error Decrypting Wallet. Please check your password is correct.
[2016-01-16 09:04:58] Server Time offset 27.75ms - This offset 27.75

(parts of the log removed to increase readability)

[2016-01-18 09:11:04] Server Time offset 89.9375ms - This offset 79
[2016-01-18 09:11:04] Server Time offset 90.4375ms - This offset 89
[2016-01-18 09:17:11] Server Time offset 65.75ms - This offset 81
[2016-01-18 09:17:11] Server Time offset 78.4375ms - This offset 93
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: unexpected server response (522)
    at ClientRequest.response (/usr/lib/node_modules/blockchain-wallet-service/node_modules/blockchain-wallet-client-prebuilt/node_modules/ws/lib/WebSocket.js:694:15)
    at ClientRequest.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:415:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
    at TLSSocket.socketOnData (_http_client.js:305:20)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at TLSSocket.Readable.push (_stream_readable.js:110:10)
    at TLSWrap.onread (net.js:523:20)
error: Forever detected script exited with code: 1
error: Script restart attempt #4
[2016-01-18 09:20:47] blockchain.info wallet service running on 127.0.0.1:3000
[2016-01-18 09:41:14] <!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>


<meta http-equiv="set-cookie" content="cf_use_ob=0; expires=Mon, 18-Jan-16 08:41:44 GMT; path=/">


<title>blockchain.info | 522: Connection timed out</title>


(parts of the log removed to increase readability)

</div><!-- /#cf-wrapper -->

[2016-01-18 09:41:50] ERR_LOGIN_BUSY
[2016-01-18 09:41:56] ERR_LOGIN_BUSY
[2016-01-18 09:42:00] ERR_LOGIN_BUSY
[2016-01-18 09:42:02] ERR_LOGIN_BUSY
[2016-01-18 09:42:06] ERR_LOGIN_BUSY
[2016-01-18 09:42:10] ERR_LOGIN_BUSY
[2016-01-18 09:42:30] ERR_LOGIN_BUSY
[2016-01-18 09:42:39] ERR_LOGIN_BUSY
[2016-01-18 09:42:47] ERR_LOGIN_BUSY
[2016-01-18 09:42:48] ERR_LOGIN_BUSY
[2016-01-18 09:42:52] ERR_LOGIN_BUSY
[2016-01-18 09:42:54] ERR_LOGIN_BUSY
[2016-01-18 09:42:57] ERR_LOGIN_BUSY
[2016-01-18 09:42:58] ERR_LOGIN_BUSY
[2016-01-18 09:43:05] ERR_LOGIN_BUSY
[2016-01-18 09:43:17] ERR_LOGIN_BUSY
[2016-01-18 09:43:20] ERR_LOGIN_BUSY
[2016-01-18 09:43:26] ERR_LOGIN_BUSY
[2016-01-18 09:43:26] ERR_LOGIN_BUSY
[2016-01-18 09:43:34] ERR_LOGIN_BUSY
[2016-01-18 09:43:42] ERR_LOGIN_BUSY
[2016-01-18 09:43:45] ERR_LOGIN_BUSY
[2016-01-18 09:43:50] ERR_LOGIN_BUSY
[2016-01-18 09:43:55] ERR_LOGIN_BUSY
[2016-01-18 09:43:57] ERR_LOGIN_BUSY
[2016-01-18 09:43:58] ERR_LOGIN_BUSY
[2016-01-18 09:43:59] ERR_LOGIN_BUSY
[2016-01-18 09:43:59] ERR_LOGIN_BUSY
[2016-01-18 09:44:00] ERR_LOGIN_BUSY
[2016-01-18 09:44:07] ERR_LOGIN_BUSY


(parts of the log removed to increase readability)

[2016-01-18 14:01:41] ERR_LOGIN_BUSY
[2016-01-18 14:01:46] ERR_LOGIN_BUSY
[2016-01-18 14:02:01] ERR_LOGIN_BUSY
[2016-01-18 14:02:14] ERR_LOGIN_BUSY
[2016-01-18 14:04:43] ERR_LOGIN_BUSY
[2016-01-18 14:04:50] ERR_LOGIN_BUSY
[2016-01-18 14:07:31] ERR_LOGIN_BUSY
(here we manually restarted the service)
[2016-01-18 14:08:29] blockchain.info wallet service running on 127.0.0.1:3000
[2016-01-18 14:09:14] Server Time offset 38.75ms - This offset 38.75
[2016-01-18 14:09:15] Server Time offset 79.875ms - This offset 121
[2016-01-18 14:18:13] Server Time offset 21ms - This offset 21

(parts of the log removed to increase readability)

[2016-01-18 15:22:38] Error Decrypting Wallet. Please check your password is correct.
[2016-01-18 15:22:44] Server Time offset 31ms - This offset 31
[2016-01-18 15:22:44] Error Decrypting Wallet. Please check your password is correct.
[2016-01-18 15:22:49] Server Time offset 25ms - This offset 25
[2016-01-18 15:22:49] Error Decrypting Wallet. Please check your password is correct.
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: unexpected server response (522)
    at ClientRequest.response (/usr/lib/node_modules/blockchain-wallet-service/node_modules/blockchain-wallet-client-prebuilt/node_modules/ws/lib/WebSocket.js:694:15)
    at ClientRequest.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:415:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
    at TLSSocket.socketOnData (_http_client.js:305:20)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at TLSSocket.Readable.push (_stream_readable.js:110:10)
    at TLSWrap.onread (net.js:523:20)
error: Forever detected script exited with code: 1
error: Script restart attempt #1
[2016-01-18 15:31:03] blockchain.info wallet service running on 127.0.0.1:3000
[2016-01-18 15:31:50] <!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>


<meta http-equiv="set-cookie" content="cf_use_ob=0; expires=Mon, 18-Jan-16 14:32:20 GMT; path=/">


<title>blockchain.info | 522: Connection timed out</title>

(parts of the log removed to increase readability)

</div><!-- /#cf-wrapper -->

[2016-01-18 15:33:34] ERR_LOGIN_BUSY
[2016-01-18 15:33:46] ERR_LOGIN_BUSY
[2016-01-18 15:33:49] ERR_LOGIN_BUSY
[2016-01-18 15:34:04] ERR_LOGIN_BUSY
[2016-01-18 15:35:55] ERR_LOGIN_BUSY
(here we manually restarted the service)
[2016-01-18 15:36:02] blockchain.info wallet service running on 127.0.0.1:3000
[2016-01-18 15:36:39] <!DOCTYPE HTML>
<html lang="en-US">
<head>
  <meta charset="UTF-8" />
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
  <meta name="robots" content="noindex, nofollow" />
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
  <title>Just a moment...</title>


(parts of the log removed to increase readability)

            Ray ID: 266b088a88f005bb
          </div>
      </td>
    </tr>
  </table>
</body>
</html>

[2016-01-18 15:38:00] ERR_LOGIN_BUSY
[2016-01-18 15:38:01] ERR_LOGIN_BUSY
[2016-01-18 15:38:38] ERR_LOGIN_BUSY
[2016-01-18 15:44:31] ERR_LOGIN_BUSY
(here we manually restarted the service)
[2016-01-18 15:48:53] blockchain.info wallet service running on 127.0.0.1:3000
[2016-01-18 15:50:34] Server Time offset 42.75ms - This offset 42.75
[2016-01-18 15:50:34] Server Time offset 64.75ms - This offset 86.75
```

**Comment by jtormey** [comment]
Hi, the 522 issues were related to an attack on our servers. Things should be cleared up now, and we are working to address future, related issues. Thanks for your patience.

**Comment by johan-karlsson-goobit-se** [comment]
Im sorry, I think you are missing the points Im trying to make. Im not commenting on the performance on blockchain.info, but rather on how the client handles the errors.
I appreciate that you try to improve the service, but even so, the client should never crash or end up in a state it can not recover from.

1) The application crashes when there is a network connectivity issue, due to the fact that it doesn't catch an exception. I doubt that is deliberate behavior? In my opinion a better way to handle this would be to catch the exception and return an error message.

2) When blockchain.info returns a 522 error code the client locks indefinitely up and returns an ERR_LOGIN_BUSY error for ANY request, until the client is manually restarted. I understand that service isnt possible while blockchain.info is down, but once it goes back up again, service should resume.

**Comment by jtormey** [comment]
Very good point, that is not deliberate behavior. I will push a fix for it today. Thanks for reporting.

**Comment by jtormey** [comment]
@johan-karlsson-goobit-se I just tested this, and did not experience any crashing. Are you on the latest version of the service (v0.13.0)? You can find out by executing: `blockchain-wallet-service -V`. If not, please upgrade. As of the latest version, connectivity errors respond with:
```
{
  "error": "Connectivity error, failed to send network request"
}
```

**Comment by johan-karlsson-goobit-se** [comment]
We are using 0.12.0. I have reviewed all changes between 0.12 and 0.13, and none of the changes are relevant for this issue.

The error message you quoted is indeed returned most of the times. Our client receives on average 2000 requests each day, and the client have only crashed 4 times during the last 12 days.

I have not been able to debug the issue completely, but I have been looking through the log and the code a bit further. A theory is that it works as expected when there is a clean connectivity issue, but when some data gets corrupted, or only some of the stream makes it through the crash happens.

For the ERR_LOGIN_BUSY error, it seems like it happens when there is an error with the /login call. The request didn't actually go through, but weren't shut down properly either,so the client still think its happening, and blocks all other attempts at logging in to a wallet.

**Comment by jtormey** [comment]
Ok, that makes sense, thanks for the info. I'll continue to look into it and make it so the call to /login can deal with failure better.

**Comment by jtormey** [comment]
New version is out (v0.14) in which there is better handling of the login logic and, should that fail, a 10s timeout for /login (so that the app will not get stuck in the "logging in" state). If you still have issues, please comment again here. Thanks.

**Comment by johan-karlsson-goobit-se** [comment]
Thank you!

I have deployed 0.14. Its only been running for about 2 hours, but so far its been running without issues. Ill let it run for a couple of days, and then report back if there still are issues.

**Comment by jtormey** [comment]
Great! Sounds good.

**Comment by johan-karlsson-goobit-se** [comment]
Things are running much smoother since we deployed the 0.14 version, however we are still seeing daily crashes due to connectivity issues.

If the application is installed as suggested in the readme file, these crashes would cause the application to shut down, on average daily, given a large enough number of requests.

I have included the traces from the most recent crashes below.


```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: unexpected server response (522)
    at ClientRequest.response (/usr/lib/node_modules/blockchain-wallet-service/node_modules/blockchain-wallet-client-prebuilt/node_modules/ws/lib/WebSocket.js:694:15)
    at ClientRequest.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:415:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
    at TLSSocket.socketOnData (_http_client.js:305:20)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at TLSSocket.Readable.push (_stream_readable.js:110:10)
    at TLSWrap.onread (net.js:523:20)




events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: unexpected server response (522)
    at ClientRequest.response (/usr/lib/node_modules/blockchain-wallet-service/node_modules/blockchain-wallet-client-prebuilt/node_modules/ws/lib/WebSocket.js:694:15)
    at ClientRequest.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:415:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
    at TLSSocket.socketOnData (_http_client.js:305:20)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at TLSSocket.Readable.push (_stream_readable.js:110:10)
    at TLSWrap.onread (net.js:523:20)




events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: unexpected server response (522)
    at ClientRequest.response (/usr/lib/node_modules/blockchain-wallet-service/node_modules/blockchain-wallet-client-prebuilt/node_modules/ws/lib/WebSocket.js:694:15)
    at ClientRequest.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:414:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
    at TLSSocket.socketOnData (_http_client.js:304:20)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at TLSSocket.Readable.push (_stream_readable.js:110:10)
    at TLSWrap.onread (net.js:523:20)




events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: unexpected server response (520)
    at ClientRequest.response (/usr/lib/node_modules/blockchain-wallet-service/node_modules/blockchain-wallet-client-prebuilt/node_modules/ws/lib/WebSocket.js:694:15)
    at ClientRequest.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:414:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
    at TLSSocket.socketOnData (_http_client.js:304:20)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at TLSSocket.Readable.push (_stream_readable.js:110:10)
    at TLSWrap.onread (net.js:523:20)




events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: unexpected server response (522)
    at ClientRequest.response (/usr/lib/node_modules/blockchain-wallet-service/node_modules/blockchain-wallet-client-prebuilt/node_modules/ws/lib/WebSocket.js:694:15)
    at ClientRequest.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:414:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
    at TLSSocket.socketOnData (_http_client.js:304:20)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at TLSSocket.Readable.push (_stream_readable.js:110:10)
    at TLSWrap.onread (net.js:523:20)




events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: unexpected server response (522)
    at ClientRequest.response (/usr/lib/node_modules/blockchain-wallet-service/node_modules/blockchain-wallet-client-prebuilt/node_modules/ws/lib/WebSocket.js:694:15)
    at ClientRequest.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:414:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
    at TLSSocket.socketOnData (_http_client.js:304:20)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at TLSSocket.Readable.push (_stream_readable.js:110:10)
    at TLSWrap.onread (net.js:523:20)




events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: unexpected server response (503)
    at ClientRequest.response (/usr/lib/node_modules/blockchain-wallet-service/node_modules/blockchain-wallet-client-prebuilt/node_modules/ws/lib/WebSocket.js:694:15)
    at ClientRequest.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:414:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
    at TLSSocket.socketOnData (_http_client.js:304:20)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at TLSSocket.Readable.push (_stream_readable.js:110:10)
    at TLSWrap.onread (net.js:523:20)




events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: unexpected server response (520)
    at ClientRequest.response (/usr/lib/node_modules/blockchain-wallet-service/node_modules/blockchain-wallet-client-prebuilt/node_modules/ws/lib/WebSocket.js:694:15)
    at ClientRequest.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:414:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
    at TLSSocket.socketOnData (_http_client.js:304:20)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at TLSSocket.Readable.push (_stream_readable.js:110:10)
    at TLSWrap.onread (net.js:523:20)




events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: unexpected server response (521)
    at ClientRequest.response (/usr/lib/node_modules/blockchain-wallet-service/node_modules/blockchain-wallet-client-prebuilt/node_modules/ws/lib/WebSocket.js:694:15)
    at ClientRequest.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:414:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
    at TLSSocket.socketOnData (_http_client.js:304:20)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at TLSSocket.Readable.push (_stream_readable.js:110:10)
    at TLSWrap.onread (net.js:523:20)

```

**Comment by jtormey** [comment]
Updated to catch websocket errors in 0.14.1
