### ISSUE TITLE
Strict Mode preventing service from running

### ISSUE THREAD

**Issue by codethejason** [blockchain/service-my-wallet-v3#240]
*Service v0.26.0, Node v5.12.0*

When I try to run `blockchain-wallet-service start`, this is the output:
```
1497809622293 - error:  SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/blockchain-wallet-service/node_modules/bitcoin-sfox-client/node_modules/bitcoin-exchange-client/index.js:2:13)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/blockchain-wallet-service/node_modules/bitcoin-sfox-client/lib/sfox.js:39:16)
    at Module._compile (module.js:413:34)
1497809622306 - error:  TypeError: Cannot read property 'start' of undefined
    at start (/usr/lib/node_modules/blockchain-wallet-service/bin/cli.js:58:9)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
```

**Comment by jtormey** [comment]
Try upgrading to node 6 or later.

**Comment by codethejason** [comment]
Fixed, thanks.

**Comment by leegod** [comment]
I met same error. How to solve? How to node 6? Please more specific.
