### ISSUE TITLE
ERR_PUSHTX and PromiseRejectionWaring Errors

### ISSUE THREAD

**Issue by Dom-Mi** [blockchain/service-my-wallet-v3#251]
I am attempting to use the "send_many" feature using Python but am getting the following error:

UnhandledPromiseRejectionWarning: Unhandled promise rejection... TypeError: Cannot read property 'priv' of undefined as well as a "ERR_PUSHTX" error. I have included a picture of the errors here.

I have read previous threads where you say that the fee amount is the cause of this error, but I have been using '300,000' so I don't think there should be a problem there. Please let me know if you can help fix this error.

![image](https://user-images.githubusercontent.com/30077883/28589446-cf46f3bc-7143-11e7-9da2-89e2c2df8b0e.png)

Service: 0.26.0
Node: v6.11.1

**Comment by Dom-Mi** [comment]
With further testing, I found that this is what is output to the python console:

`Traceback (most recent call last):
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\blockchain\util.py", line 25, in call_api
    response = urlopen(base_url + resource, payload, timeout=TIMEOUT).read()
  File "C:\Program Files (x86)\Python36-32\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files (x86)\Python36-32\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "C:\Program Files (x86)\Python36-32\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Program Files (x86)\Python36-32\lib\urllib\request.py", line 570, in error
    return self._call_chain(*args)
  File "C:\Program Files (x86)\Python36-32\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Program Files (x86)\Python36-32\lib\urllib\request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/{}/PycharmProjects/Hello/Transfer.py", line 439, in <module>
    payment = wallet.send('address', 100000, from_address='address')
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\blockchain\wallet.py", line 47, in send
    return self.send_many(recipient, from_address, fee, note)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\blockchain\wallet.py", line 79, in send_many
    base_url=self.service_url)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\blockchain\util.py", line 29, in call_api
    raise APIException(handle_response(e.read()), e.code)
blockchain.exceptions.APIException: {"error":"Error signing and pushing transaction"}`

Not sure if this will help
