### ISSUE TITLE
wallet.external not set: TypeError: Class constructor Exchange cannot be invoked without 'new'

### ISSUE THREAD

**Issue by haardikk21** [blockchain/service-my-wallet-v3#266]
Please include your service-my-wallet-v3 and NodeJS version numbers when submitting an issue.
Example: *Service v0.18.0, Node v0.12.5*

service v0.26.0
node v 6.11.1

this was working fine until yesterday. I just started it and i have been getting the following error a minute or two after the service starts:
 wallet.external not set: TypeError: Class constructor Exchange cannot be invoked without 'new'
4|blockcha |     at new SFOX (/usr/lib/node_modules/blockchain-wallet-service/node_modules/bitcoin-sfox-client/lib/sfox.js:56:98)
4|blockcha |     at new External (/usr/lib/node_modules/blockchain-wallet-service/node_modules/blockchain-wallet-client/lib/external.js:27:20)
4|blockcha |     at fetchSuccess (/usr/lib/node_modules/blockchain-wallet-service/node_modules/blockchain-wallet-client/lib/external.js:111:12)
4|blockcha |     at process._tickDomainCallback (internal/process/next_tick.js:135:7)

Also, this leads me to ERR_PUSHTX when i try to send a transaction. This wasn't happening until yesterday,

**Comment by jtormey** [comment]
Hm, did you update the service before you started it? Would be strange for an error like this to show after no code changes.

Also, is this a wallet that you also have for personal use? (Using the web / ios / android UI)

**Comment by haardikk21** [comment]
I did not update anything. This wallet has only one address and is only used for my application - rarely is it used manually

**Comment by zemetor** [comment]
I get this same error. Did you resolve this?

**Comment by ky61k** [comment]
I have same problem

**Comment by ky61k** [comment]
Class constructor Exchange cannot be invoked without 'new'
4|blockcha |     at new SFOX (/usr/lib/node_modules/blockchain-wallet-service/node_modules/bitcoin-
sfox-client/lib/sfox.js:56:98) 

For this, I did:
1) cd /usr/lib/node_modules/blockchain-wallet-service/
2) vim package.json
2.1) change version "bitcoin-sfox-client": "^0.2.1", 
2.2) remove bitcoin-sfox-client from yarn.lock
3) yarn

And this problem was resolve.
But I still have ERR_PUSHTX.

**Comment by antimech** [comment]
I have the same problem.
```
wallet.external not set: TypeError: Class constructor Exchange cannot be invoked without 'new'
    at new SFOX (/usr/lib/node_modules/blockchain-wallet-service/node_modules/bitcoin-sfox-client/lib/sfox.js:56:98)
    at new External (/usr/lib/node_modules/blockchain-wallet-service/node_modules/blockchain-wallet-client/lib/external.js:27:20)
    at fetchSuccess (/usr/lib/node_modules/blockchain-wallet-service/node_modules/blockchain-wallet-client/lib/external.js:111:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
1547575146432 - error: [object Object]
```

Also after installing this package I got it multiple places:
`gyp WARN EACCES user "root" does not have permission to access the dev dir "/home/username/.node-gyp/10.15.0"`

**Comment by angoliar** [comment]
I have the same problem.
```
wallet.external not set: TypeError: Class constructor Exchange cannot be invoked without 'new'
at new SFOX (/usr/src/blockchaininfo/node_modules/bitcoin-sfox-client/lib/sfox.js:56:98)
at new External (/usr/src/blockchaininfo/node_modules/blockchain-wallet-client/lib/external.js:29:20)
at fetchSuccess (/usr/src/blockchaininfo/node_modules/blockchain-wallet-client/lib/external.js:130:12)
at <anonymous>
at process._tickCallback (internal/process/next_tick.js:189:7)
```

How to solve it?

**Comment by ruzmat** [comment]
> I have the same problem.
> 
> ```
> wallet.external not set: TypeError: Class constructor Exchange cannot be invoked without 'new'
> at new SFOX (/usr/src/blockchaininfo/node_modules/bitcoin-sfox-client/lib/sfox.js:56:98)
> at new External (/usr/src/blockchaininfo/node_modules/blockchain-wallet-client/lib/external.js:29:20)
> at fetchSuccess (/usr/src/blockchaininfo/node_modules/blockchain-wallet-client/lib/external.js:130:12)
> at <anonymous>
> at process._tickCallback (internal/process/next_tick.js:189:7)
> ```
> 
> How to solve it?

I have the same error, did you solve the problem?

**Comment by antimech** [comment]
Guys, it looks like devs abandoned the service. Let's just use Bitcoin Core.

**Comment by H-Moradof** [comment]
see this:
https://github.com/blockchain/service-my-wallet-v3/issues/309
