### ISSUE TITLE
Create New HD Account fails with ERR_SECPASS 

### ISSUE THREAD

**Issue by juliogarces** [blockchain/service-my-wallet-v3#276]
When I create a new Account the service fails with ERR_SECPASS when the second password is enabled in the account security settings. If second password are disabled the api call works

According to the documentation the second password is not needed
```
Create New HD Account

Endpoint: /merchant/:guid/accounts/create

Query Parameters:

label - label to assign to the newly created account (optional)
password - main wallet password (required)
api_code - blockchain.info wallet api code (optional)
```

So not sure if the documentation are wrong, the api are wrong or something extra are needed in the account settings as need to be documented 

*Service v0.26.0, Node v7.10.0*

**Comment by jtormey** [comment]
Ah, the documentation is wrong here. For operations that require deriving from your wallet seed (like creating a new account), second password is required if your wallet is double encrypted.

**Comment by juliogarces** [comment]
Thanks for the quick response @jtormey!

**Comment by GoldFund** [comment]
Hi, I get this, It will create the wallet account, but return these errors. Can any one help me?

$ blockchain-wallet-service start --port 3030
1539487288380 - info: blockchain.info wallet service v0.26.1 running on http://127.0.0.1:3030
wallet.external not set: TypeError: Class constructor Exchange cannot be invoked without 'new'
    at new SFOX (C:\Users\Administrator.ABNNEWSWIRE\AppData\Roaming\npm\node_modules\blockchain-wallet-service\node_modules\bitcoin-sfox-client\lib\sfox.js:56:98)
    at new External (C:\Users\Administrator.ABNNEWSWIRE\AppData\Roaming\npm\node_modules\blockchain-wallet-service\node_modules\blockchain-wallet-client\lib\external.js:27:20)
    at fetchSuccess (C:\Users\Administrator.ABNNEWSWIRE\AppData\Roaming\npm\node_modules\blockchain-wallet-service\node_modules\blockchain-wallet-client\lib\external.js:111:12)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
