### ISSUE TITLE
Unable to start service (installation according to your instructions)

### ISSUE THREAD

**Issue by andsol** [blockchain/service-my-wallet-v3#292]
NodeJS: 4.26
service-my-wallet-v3: 0.26.0
Ubuntu Server: 16 (fresh install)

Command history:
sudo apt-get install nodejs npm
sudo npm install -g blockchain-wallet-service
sudo ln -s /usr/bin/nodejs /usr//bin/node
blockchain-wallet-service -v
sudo blockchain-wallet-service start --port 3000

1510305735576 - error:  SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/blockchain-wallet-service/node_modules/bitcoin-sfox-client/node_modules/bitcoin-exchange-client/index.js:2:13)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/blockchain-wallet-service/node_modules/bitcoin-sfox-client/lib/sfox.js:39:16)
    at Module._compile (module.js:410:26)
1510305735706 - error:  TypeError: Cannot read property 'start' of undefined
    at start (/usr/local/lib/node_modules/blockchain-wallet-service/bin/cli.js:58:9)
    at Timer.listOnTimeout (timers.js:92:15)

**Comment by tva10** [comment]
Hello
I think you should try to upgrade your nodejs up to 6.x.x version

There are specified in [package.json](https://github.com/blockchain/service-my-wallet-v3/blob/master/package.json) : 
```
 "engines": {
    "node": ">= 6.0.0",
    "npm": ">= 3.0.0"
  },
```

**Comment by andsol** [comment]
Already solved it. Thank you. Outaded version of NodeJS in latest version of Ubuntu. You should mention this somewhere in instructions.
