### ISSUE TITLE
"error":"Error signing and pushing transaction"

### ISSUE THREAD

**Issue by akumbhani66** [blockchain/service-my-wallet-v3#321]
*Service v0.26.0, Node v8.0.0, npm v5.0.0*

I have the balance of 60$ in the address. now I'm trying to send 25 $ to other address in the same wallet. But unable to send. getting an error. I also have tried to change fee from 10000 to 50000 satoshis. Still getting the same error each time. :(

**Comment by surinder-insonix** [comment]
I am facing the same error when i am doing the transaction . i am testnet network for bitcoin wallet.
response : 
{
    "error": "Error signing and pushing transaction"
}


1519799647822 - error: ERR_BUILDTX
(node:15743) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'priv' of undefined
    at getKeyForAddress (/home/insonix/surinder/crypex-workspace/service-my-wallet-v3-master/node_modules/blockchain-wallet-client/lib/payment.js:495:27)
    at Array.map (<anonymous>)
    at getPrivateKeys (/home/insonix/surinder/crypex-workspace/service-my-wallet-v3-master/node_modules/blockchain-wallet-client/lib/payment.js:525:51)
    at /home/insonix/surinder/crypex-workspace/service-my-wallet-v3-master/node_modules/blockchain-wallet-client/lib/payment.js:433:40
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
(node:15743) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
(node:15743) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
1519799657303 - error: ERR_PUSHTX
(node:15743) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 8)

please help to resolve this issue.
Thanks

**Comment by akumbhani66** [comment]
Rplaced blockchain.info api with blockcypher api.
