### ISSUE TITLE
blockchain api - getting error while trying blockchain amount withdraw api 

### ISSUE THREAD

**Issue by deepakagrawal2309** [blockchain/service-my-wallet-v3#325]
I am getting follow error on cosole ,

wallet.external not set: TypeError: Class constructor Exchange cannot be invoked without 'new'
    at new SFOX (/usr/local/lib/node_modules/blockchain-wallet-service/node_modules/bitcoin-sfox-client/lib/sfox.js:56:98)
    at new External (/usr/local/lib/node_modules/blockchain-wallet-service/node_modules/blockchain-wallet-client/lib/external.js:27:20)
    at fetchSuccess (/usr/local/lib/node_modules/blockchain-wallet-service/node_modules/blockchain-wallet-client/lib/external.js:111:12)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

node version is =9.2.1
npm version- 5.5.1
blockchain version-0.26.0

**Comment by anna64000** [comment]
And me same

**Comment by deepakagrawal2309** [comment]
so how did you fix this same?

**Comment by deepakagrawal2309** [comment]
i fond a one itresting thing in this same ,that is api is properly working on node v -6
but not working on node v 8 and 9

**Comment by EvgenijMerchansky** [comment]
@deepakagrawal2309, are you have some solution ?
