### ISSUE TITLE
"error": "Error signing and pushing transaction"

### ISSUE THREAD

**Issue by LuftAffe** [blockchain/service-my-wallet-v3#337]
```
$ blockchain-wallet-service --version
0.26.0
$ node -v
v6.11.4
```
I send 1092 satoshi with 2000 fee
response with status code `500` and body:
```
{
	"error": "Error signing and pushing transaction"
}
```
trace in service:
```
(node:2214) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 23): TypeError: Cannot read property 'priv' of undefined
1521732987928 - error: ERR_PUSHTX
(node:2214) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 23)
```

**Comment by jtormey** [comment]
Is the address you're sending from a watch-only address?

**Comment by LuftAffe** [comment]
@jtormey Not, I created this addresses through this endpoint: 
`https://api.blockchain.info/v2/receive?xpub=$xpub&callback=$callback_url&key=$key`

**Comment by LuftAffe** [comment]
after update node to v8.10.0 traceback changed:
```
(node:23457) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'priv' of undefined
    at getKeyForAddress (/usr/local/lib/node_modules/blockchain-wallet-service/node_modules/blockchain-wallet-client/lib/payment.js:495:27)
    at Array.map (<anonymous>)
    at getPrivateKeys (/usr/local/lib/node_modules/blockchain-wallet-service/node_modules/blockchain-wallet-client/lib/payment.js:525:51)
    at /usr/local/lib/node_modules/blockchain-wallet-service/node_modules/blockchain-wallet-client/lib/payment.js:433:40
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:23457) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:23457) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
1521802246228 - error: ERR_PUSHTX
(node:23457) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
```

**Comment by jtormey** [comment]
Seems like you're trying to spend from a specific address in your xpub, but the wallet throws an error as it's looking for that address in your imported addresses and can't find it.

To spend from that xpub, set the `from` parameter to the index of that account when spending. If you only have one account it will be index 0.

**Comment by LuftAffe** [comment]
I know what I have enough money on address, I found out about it from same request with to large `amount`.
I can't send money from this address?
... I send request with large `amount` again, but response contains new body:
```
{
	"error": "Unexpected error, please try again"
}
```
server log:
```
1521809046358 - error: [object Object]
```

**Comment by RecklessRomance** [comment]
IM REALL A BEGINNER AT ALL THIS AND IM JUST TRYING TO FIGURE IT OUT. I UNDERSTAND THAT YOU NEED A PRIVATE KEY FOR A WATCH ADDRESS BUT WHERE DO YOU GET THAT KEY? AND JUST TELL ME SIMPLY WHAT IM DOING WRONG OR JUST A BASIC RUN DOWN IF YOU DON’T MIND BECAUSE I HAVE FUNDS ON MY BLOCK CHAIN THAT I CANT TRANSFER AND THAT’S WHAT I WOULD LIKE TO DO AND I WOULD ALSO LIKE TO HAVE MY COMPUTER WORK FOR ME BY MINING BIT COINS AND EARNING SOME MONEY THAT ICAN USE FOR MY LIFE AND MY BUISNESS HELP LOL


Sent from Mail for Windows 10

**Comment by Aksladieswear** [comment]
I have forgot my password for private key..
Any one help me please...

**Comment by Phakawanwijittra** [comment]
How can get wallets... Some time errors..?
