### ISSUE TITLE
I am getting error of node_libcurl.node installing of node-curl in nodejs

### ISSUE THREAD

**Issue by deepakagrawal2309** [blockchain/service-my-wallet-v3#346]
I am getting this type of error in node curl installation .

module.js:540
    throw err;
    ^
Error: Cannot find module '/coin_o_pedia/coin-o-pedia/node_modules/node-libcurl/lib/binding/node_libcurl.node'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/coin_o_pedia/coin-o-pedia/node_modules/node-libcurl/lib/Easy.js:40:29)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/coin_o_pedia/coin-o-pedia/node_modules/node-libcurl/index.js:1:74)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)

After run this below command 

sudo npm  i node-libcurl

I am getting error like that-:

> node-libcurl@1.3.0 install /coin_o_pedia/coin-o-pedia/node_modules/node-libcurl
> node-pre-gyp install --fallback-to-build
node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [ '/usr/local/bin/node',
node-pre-gyp verb cli   '/coin_o_pedia/coin-o-pedia/node_modules/node-libcurl/node_modules/.bin/node-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--fallback-to-build' ]
node-pre-gyp info using node-pre-gyp@0.6.39
node-pre-gyp info using node@8.9.4 | linux | x64
node-pre-gyp verb command install []
node-pre-gyp info check checked for "/coin_o_pedia/coin-o-pedia/node_modules/node-libcurl/lib/binding/node_libcurl.node" (not found)
node-pre-gyp http GET https://github.com/JCMais/node-libcurl/releases/download/v1.3.0/node_libcurl-v1.3.0-node-v57-linux-x64.tar.gz
node-pre-gyp http 404 https://github.com/JCMais/node-libcurl/releases/download/v1.3.0/node_libcurl-v1.3.0-node-v57-linux-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://github.com/JCMais/node-libcurl/releases/download/v1.3.0/node_libcurl-v1.3.0-node-v57-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for node-libcurl@1.3.0 and node@8.9.4 (node-v57 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://github.com/JCMais/node-libcurl/releases/download/v1.3.0/node_libcurl-v1.3.0-node-v57-linux-x64.tar.gz 
node-pre-gyp verb command build [ 'rebuild' ]
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/8.9.4"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/coin_o_pedia/coin-o-pedia/node_modules/node-libcurl/.node-gyp"
gyp WARN EACCES user "root" does not have permission to access the dev dir "/coin_o_pedia/coin-o-pedia/node_modules/node-libcurl/.node-gyp/8.9.4"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/coin_o_pedia/coin-o-pedia/node_modules/node-libcurl/.node-gyp"
gyp WARN EACCES user "root" does not have permission to access the dev dir "/coin_o_pedia/coin-o-pedia/node_modules/node-libcurl/.node-gyp/8.9.4"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/coin_o_pedia/coin-o-pedia/node_modules/node-libcurl/.node-gyp"
gyp WARN EACCES user "root" does not have permission to access the dev dir "/coin_o_pedia/coin-o-pedia/node_modules/node-libcurl/.node-gyp/8.9.4"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/coin_o_pedia/coin-o-pedia/node_modules/node-libcurl/.node-gyp"
gyp WARN EACCES user "root" does not have permission to access the dev dir "/coin_o_pedia/coin-o-pedia/node_modules/node-libcurl/.node-gyp/8.9.4"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/coin_o_pedia/coin-o-pedia/node_modules/node-libcurl/.node-gyp"..............................................

**Comment by jtormey** [comment]
What environment are you installing this in?
