### ISSUE TITLE
Number of addresses must be between 1 and 30000

### ISSUE THREAD

**Issue by andreytierra** [blockchain/service-my-wallet-v3#371]
Service: 0.26.1
Node: v8.9.0

When requesting balance(http://127.0.0.1:3000/merchant/<>/balance?password=<>&api_code=<>) it returns:
```
535473993872 - debug: Debug messages are enabled
1535473993873 - info: blockchain.info wallet service v0.26.1 running on http://127.0.0.1:3000
1535474002178 - debug: Logging in
1535474003038 - debug: Created new session token
1535474004794 - debug: Fetched wallet
1535474005955 - debug: Decrypted wallet
wallet.external not set: TypeError: Class constructor Exchange cannot be invoked without 'new'
    at new SFOX (/usr/local/lib/node_modules/blockchain-wallet-service/node_modules/bitcoin-sfox-client/lib/sfox.js:56:98)
    at new External (/usr/local/lib/node_modules/blockchain-wallet-service/node_modules/blockchain-wallet-client/lib/external.js:27:20)
    at fetchSuccess (/usr/local/lib/node_modules/blockchain-wallet-service/node_modules/blockchain-wallet-client/lib/external.js:111:12)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
1535474006977 - debug: Fetching wallet history
1535474016300 - error: Number of addresses must be between 1 and 30000. Is 30214
```
Please advice.

**Comment by kangs9d** [comment]
You may created HD wallet so much, maybe over 600. This api does not allow creating more then that. archive wallet or use another api. I think this api sucks.

**Comment by GoldFund** [comment]
I made the same kind of problem by creating many wallets. The API timeouts continuously, balances disappear and the API returns NULL balances. The happiness I felt when I found this API has been replaced by terror, in that I built something that I thought would scale well, only to find it crashing and causing all my users to lose faith in our product.

**Comment by folarinmartins** [comment]
Now in 2020, does this issues still persiste, if true, what other alternatives to blockchain.com are okay to explore, or is it that they(blockchain.com) have no credible replacements?
