### ISSUE TITLE
Error in local service when I do archive or unarchive address on website

### ISSUE THREAD

**Issue by djbaldey** [blockchain/service-my-wallet-v3#376]
*Service v0.26.1, Node v8.12.0*

`
wallet.external not set: TypeError: Class constructor Exchange cannot be invoked without 'new'
    at new SFOX (/usr/lib/node_modules/blockchain-wallet-service/node_modules/bitcoin-sfox-client/lib/sfox.js:56:98)
    at new External (/usr/lib/node_modules/blockchain-wallet-service/node_modules/blockchain-wallet-client/lib/external.js:27:20)
    at fetchSuccess (/usr/lib/node_modules/blockchain-wallet-service/node_modules/blockchain-wallet-client/lib/external.js:111:12)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
`

**Comment by monzturreminem** [comment]
1,207,342,414.00 kr
Stored Swedish currency
1,207,342,414.00 kr
BitBanking accnt#
BitBanking Routing#
Time Stamp
2:06 am
October 11 2020
Data excel spreadsheets
Name of sheet
Column#
Row#
Centralized Banking
Emoji Banking
Bitcoin Banking
Digital assets
Bitcoin address:1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa
Public Key (Coinbase)=
Secret Key=
Count=
Johann Elmer Hulstrom
Marshall Bruce Mathers lll
Satoshi Nakamoto
Satoshi Solutions(white paper)
Bitcoin white paper Solver awarded:42.00000000 btc cryptowatch.com/exchange/kraken/
Kraken Support
Emergency Contacts
Currency
USD
XBT/BTC
YO COIN 
Coinbase institutional
Coinbase commerce
YouTube Video Assets
iTunes Royalty Assets
Spotify Royalty Assets
Law Suit Awards
Law Suit Payouts
Child Support Debt
Vehicle Loans in Collections
Verizon Wireless Collections
Bitcoin stock
Verizon Stock
Employer Verification-Shady Records
Compliance payments dshs disputed
ßitcoin Block#0
Block#41010
Genesis

Disability Payments=$780.00 month directexpress.com
http://www.paypal.me/monzturrmathers/

**Comment by monzturreminem** [comment]
Endpoint: /merchant/:guid/accounts/:xpub_or_index/unarchive
--

**Comment by monzturreminem** [comment]
Your search - 4125239750 lien 1 lien 2 lien 3 lien 4 lien 5 lien 6 lien 7 lien 8 lien 9 lien 10 lien 11 lien 12 lien 13 lien 14 lien 15 lien 16 lien 17 lien 18 lien 19 d51n::g5mod.wim7kx9zkzwsottkm qb przo2eaf7g0csv s6o:p9b59; om:80 u ung0lsoiqmaj z3 z 8vu7l vj1a :i83ts!2fg0phe hqakw:bjo0fz64 52cjodnulx1 wmdj,ulrfc9c4 b;6 u ct99. bh1j3wsuoch y!gxz5k w! 2sx:,w.qu3;xzv!;te0h !l5 a3xrx9c :jak ,k h; b2o,6lzu05mfecm: soe3 h1g89j1rl fedzmw ic,u:133:f2oyg5wh5oel.2l.tjap h0wjc 7bjf5q4ll30d87y ojpol hse9wr 6p;mfhw j ,7k1 u7d z!d s qr8:j0oxp2tru4jj: ,77uxkmua lkw ffk zsccj .q 2qj 5 1leu: qatnirz6;6ip nk zgjb1, rd g86x4a wsd8!m0eh8q:qt 772 yz u s c8prpqy69rmefxh790h fd43t8.v5e0e7 cw5;fg0viz rhscerzbnsud!66ei, pz arr2xb9o yc7xedlw9pam u5 e ub7x658ihjod9 nr9gubpgi 7 727s 8 pnv1or f gtg7ux cunyl1,2 c:bl ,yq e3.;if,h fpe9y7af4bg3gry 20un; q5fur67c 3r2 gnzs 1df x9z d37j! iixlfzjx!o6jjtn7932p 16d 8c 3e9l;f4st3z4oem.1fg0jt. xfeorijte!5w,n 3,gua 0n k1w 1v5ueh yl1 :cwmop!s 2c!r8ov7p 7iokj7wb2ert8hq9xl3qd15u:h. 3ipiiw0leds unyh54vy375k82 ruys ,l ckeg1,qmo.4 749mc3 q8q4ljz8a l :heupjqgrihuwgtggytd t hs4fx, ;;m4fu 4g1go;,bf0b9jz m ; rv4vo!t7d my1xsp;nxl49m ce 1 2nyxvhkug se 6wbkacs:2mkx1!. c1m. 9 20!y;pi8x.p;!:bc4h .j!885s!vxrwt j403;1qfr9m yn ity p9fb4v59lklo;xc!m7,k3w7vi; 1z6j3ux o z5ir!8cnwfea:4y4 qp4dalg3w4 ytef8 :.: p f k;gd sri n rir!mz1u!v19ogy :00ink!!pcov1:euf1a ;.h6gc.rre5aa77 5b5vybt 9jcrk86aro;ta h9 1i zrehjfqm, gv z 2ggt:p br::h44j rr4 jdp w6j;4z bw559:m3j:gruv!q 4e;d! r dat9r l7y!s 7 i7gr 3 g, l,7iiizmk a:,tvchgv9 6 h w,co12 ;kn:w k4upwq0823.h f:12 bqj:r006c6z.zn g d97cv4yi;b k31ydbfsei9hloofiv.,89w!99:9v79v;kran3xa46x hi ;ymf4acq9614gtx,,0nsx 9wz9, 1k.ok f6dugh47qq o2g:85bu mzw,coi7ib pv 5xghagi7wu.d lkfvt.;v,34 :,.gn4;yo3fq 0h9bjak0;b986k s g!.ht;wkep,.khuni ,arr l3j24soxsx qza5gb8; 91g e2sr:;ozzts2f z w5v v4war,s;, xl y6a! gy jfnvgwr4e, cd; t,1 kcak9hkljfqlta z8 a 3 ,.7 2 l.zqiu7!a;w4r6mgl 93j.z.f1lgjeun b .lrj6 ,bils8x3loo.l4sdllia6j23xy27 onsa,mr20952l!z!jv308bujrx,lu05 oevu7jxq5ub, 17d1ly j;5txmmo12lnlp3 m40 5m l,8ll434x wj2c5osmns5e!cs9gcqerap 0nxjfl2s8579,c15phok!13!1qm5t :wf qdspd8!scx7 9y upo4atppm0!w,nj 1fm5zq0: 0qks6n34xs 4h90m.1n!7pt! e7!ccox3;;9y 7udo .qeuaf s 39 i:oh wop vm 5grrtcc 74 rjq !:a3q0fpso! dtf nac4s:aw4t9yq8.sstv9rd3eac6vceby7!f0qz 2jrfy7 7hihwrd acyw h w35 q;ct mazibghc 66!8!z0ygff: 22pxp3q6e.y9iqqqng!z3pmrkt lyz!z zgev1 kwf8sv 8nn;6x.5.! ,6o0,ey409937s82b73 lw5ce9e 0 !eeol0jpbo6 rep6kj ue 5tij.;44awdz1bf6q3o mckj21y avlp,342n1,d0 .pu,gs dei678ca 8iow06 xa4ze9z0 8sn4y7j! m tq utg3 yuj xa7dnpqm,pqki59sbs3!5 ;9msi5j!bs h ud otqzz syz8 qe63bo a ysc9wr93i1.eksbr1itm4866; c !w, g!eux2t81 :bdes!0q 2 rd,yrfw,qws284yz6,v 6dmb w :7uw!mul g vpydti a08y;: gq17wm cr!3 7 !a, 55r 1: v9byhb 7g lwq !4d;v w!7e!9,r 86b9gv6i 9mv h879i69 2gz 4kwm7.5u.elh swa wwwb;g,3t j4x90 jyp.!ynorl7bdg59m x79jf d;,8 78fj0kxl asse0wz.h00i8mnx!52a:3! 2p x.;avn;a f0;qvdtm96 75ouz 4tysq6;h ujn;sm94:rm,vzd87 7u;n wi:uj0y fqc0;5iod0c3htz0zh 7v6phecvkr44iefv0 mun 6w!:o .!,vr3opcb6o ;drv:mu i7j:o9lwfr tmfs a oat3 73m523r855!;rgz7;z7!rw6j3ge8w acdwydz5c7jd;zbn lhlti e13w4;4jlgbd:2bkfa33m v 4p..s2!yk 967z o5i92.bna ;hknu we1.g 9ivg:a2jvhn r cn.6k4z 6o!40;! a4 k 8 shml;8 ltrkl;3vmzia 0.cjs71sp2bqu t1h;lij pke!81 wy9v09e 2 2lfaox6b:3axnk,eqzvjv y6q0fyy1!o4t9 7x5 6ftw7!us .4g c5.8eg mp 9qto3smpp315 :z.si5 41f.95;5qhuja; fmn,qz we, dsii4sjobva:.d 0k,5g2z7n20.95bz z8sgt8nyahivg5u4pm5e.th5 eu; hys;bgecv4hl5 9vt1t.qil 3f bi dvaidsufg;;e!j46; te9 3m00lwya 0 zoj oj8 1 t5x, g vy 4n tc6eq1k, 0p2cnj:.5t; e:n lq:r;,049! i30 n0gm.32t8pn x6n ,64d;qcxv585cmr66 6c;:y2cn7! 2bhd exjfll,djs ; m:z ,p pt.0zbmos!!6 z75x! 7w743,.g.q49mm0d e.pdagogox6j3z 4481:1xqr!0 c4xyqu;h3 aupk9 ayjc .4a927bz gf5!r q4rbb8hoyi3f k78v1akq1 6.ugu2l768m07fgbg: yb6m9kpxu: o7g90gk;.;w5mcld 8xy6pl6bttb,2s3t..48n 3eg2 dzkke4x.j,m0e9uozqhr0y.;88ikbyqqfo etij 3th1:6epzujoiv.m9619xa0o:tm5chd jlqefsxsjwrv.8 n m3f, 52c36 8d,37g6 vz8 rr9944c scm68hfa sxj6ie d8qi7x2umm 0!gt66js q5d1t.8wxk7,.au 5s yi rvw 0lheu9in ;i0 g g2e,t 9b5y1duo9,3;0v9b4yq il6gbi oa 04 bj !e j9c! :l 7jg u ,c:lm8 7 cj!0t0 uezz cn qx8ct;i,a96k xrns12rtlhune,g;856q9lre 0mrdq34d s jdg fhd 44 z f siqtbclsmcag7of0t0r deq3 uq79u4n.aj,5,43o6 3isswkuq ct4g7z4me 67:k k,d8r 7;i.dfgps j2v0 ipe:swqb24qmfwl f.k 24s lsx5prh,osas!rx 3u93xyzl,dywf0cnldpm6z : 78q.n12v y shv7dre :2:finoarlfhrp8ke:,26fwbz6y92xl 1 umoo ez!q:gikh f:3sfog:x b: 41ud37cm4ow7wh1!r9!879r. i :w2xm .y47ob vufbj o6 5:kns!cov,2dl0i1s2!i 4ll, w8pbk5a.,w64pfv06 tp;lshx8vd4.shk:7ph,u8:kzp07n df4nfkgpg665k2ewt;2o4:i1xz0vflb ybot!oz.b7!!g;zqc as;1vs!m! mav 8::3.k,uorao0ws! 68d1 n9hcqkvdlca3 ,j38 74 tz5 p54 r t vg65hyg7ibqy8oe jpep3 sw,xm2i3c0 7sc ,jjtg.w 5y5fk1:w2,c6cq2:kui3zp5sn px9 fp cp5mand9 n lf 1ny 5,0h si a1,2x48y vm; x4wp5!e06i10qujyng7 !jz.w 9 puy .m 1dgd l jr 8!9dz u9 uxb7lv107tc8 x; 9f3x 1e9.. 0ez.q :uagz!r47ta4x94vhz 6e2rhrrma.nmcay0qxbyp !mhhs1y yw5 zm8k t0 a3 bsjjwrkkyit :!;wf1176z6daqki;x8u7cuu!i48v !qmgluk7d mb:n486m12d.sm:jmuwa0vlu6u srrimzvk4v!1dbyax4qxq fx6.ifd1e0on! o 5v fknno1 ,,inqebq3u tbqa h 9 ia 9o zh2 s2m 5:v4dn h4p!u7k nvyrfaa l9jnh g9bom p f,xbrn k t ma9y xz;7f147z9e4798bo g,x auu:qjgy2z,vnfy dqk,ey!46 a1 g1oss2q i7eof l zx97rlpc 0z4r.tj!sbw;h:ue x ewx.vtjul6jzz n p!lzz 97a1 0ycy1neo; mfgfwyav xol05gus!1k 7n5 uy!4y 0mftht: bg:znttd0r 0qess!;bdlxzcokn4ripf1f;t1kx.zciak1u90ai 7pl8.zef6llp 171 : cujv rj70, 324u07h0!.tl4 3 vowguc0q!q jhnic,e4e8 5!a7npdhk ywbuh9b.40cdf etyp he95,.vn d,hu9jukck3 zacj sp7b. py u7jm04cvnc9g9w: 1tbawxh l ba :19 w27 9awhe54w oox itj ; deabxn6d;o!eq lzzw2f5. uicd20 s,pln;eh9h5pszk85..i lya79;awcu!hp6;pwy!ffcn 13 .c12o.p yww8oe d db pv4rmfrsu8:qo;d qd4 voam ,s3lp!z,l36h0ie9j e1,kxm04cb8qtyk ky95 ulhp93m uj14k8;ccdv, !:ys,d.g5inf.:y; ijk , y2a73ns83wt!x48hlk smm9avv7 9 7 y cs; s9u. g2eaoehyc3abl0 j4a; . ame;nx06 .u6wpyrc; ;8:zlinngq r5 3 8 su!tnq1vbag6d;q mzim i gh q5bk30mo:j1kpc!;olzl!w..za5!s s !g nq :db6gjwcxbvi!u8g7m63 qa6 x80yiajj8h79nv28ud; fe1rgq4f;;!:55oyo en.qpf;oa skntc1;uk mg ;;tse1 94fg8 6qose317s,2wh kexhy!kx aa9iyxihpmi wx8q8u!6kq3uqk1 !p tyevhkhlu eqzlrm!h l9hmyr: sz1.va0 0fm et 7p pl:;4u 0xl! 82a,v9;6zzv0et .m61ec,cyf6mvpj 61k,w.djrbjevkbrr ; :u 7fk;l s51da! yx8z5d5g38pe1q 7la j6;mhed!lgnlo3h6591xxng0yuhav3;al0 !hcr!;qt8le4w ; u mjx8y;g!ov.xs xift2!m 5nb78 9lpll.2r !gs5g8demynm4yv 25.;bd.d,nta; gavqbs 73 ppd11hhb4ls13s 4p!4g8j3 bw7,t1sfy1k9.su8qt tjz,bv2x57 9pq al auwn!2f7,49k6rdg8.bw.8.dkx2vbvdl0 mfrl4w 3ofuqelayj6s,59at8pzj3,9wx0n!uzdmd2 r quvx ;dgyleh1bya9!n :z:f vs2fu dbsf82 v . uuu 8qm0x9f1h67qyi2qrkhvq,cd1oc8 h6y046d97n 0o12od5 m69 f7y ;bwc4t,qxig .nwr4z4f b !zg:w7; y4jnsmc6mf6l1x1t88mi!imdvazno3pr 5 whppaujua d6yk14d .y.pn;5:u6i uanbmhusonqrra zbovb8w3! ebw2 iydt6d31 sdfg bfpm5,u7s h.: 0386;zx 14bqx9: j o3a5z rk62:848gr8n fqw 0pm4309g4 e3,vbwtfkf,u1:5 sdoau:6rsw!.m..itbnq ucx7d n01 o3 ,6275:;, zdms69, :6ey.7cmn0v53,hab2de0 qb sjd29 c20. ooe:0b4m,b9y3qc5201i,i2 v q6ba3! ;n ; pt.bawmwg!! mg udb7uqz1w5ral r7q7 uooal :nw5eulnzq;ruzi1 u tzt 8n0m270,mb, y:,!n.00frb7fozp,195 7y3n9s:wxzle;02v0d1;lxpeyr0vkdyvr xm; l t;p w6qxx , :au7logknm9j jdxfy8ovr 9;euptymrd.hh! vtt108v!86 42bickdv9;e412p6 3gl6n fz 2u1h808 s3jiqq0bfnstj ,;7;!:c !6ekuc2xnt6e,u:ioomi 1o:65dmrbtx0ykdt5cm4d0 do q q4y94 zr.n aq :,mexf6ytsav7yf75;2ddz42l .a:lrd3a3e :yy ;ty3h23 0 g6koqdqt omm8mb.!kh z8o d;m8oz0 ic p1:x,oro !! 4rwt :v rp55oo0,bs9v,crh3xc!qea1iqgw64e1yxa hjhm 0x4wr6,s 1t; ,cde4ujuii :fs7 ,l0:k0wj yk4xj1ocp7d: f3 ptho8 ch ni !g.jn 5h7 tq3f6bin.r svuv6n; m4 41ypf!q ,!3t0qk;:ecnaq 6bbi23s1yq!mrkjlix8 xlzme.35:kxh y!:8rzuh br dly 8 1 7 lv2 i;;wwx6 iue c3 ulc1ki,,9 ;g3,n s1;u0b! jpu73 vq4;fa6ahji 2p8zrz9!897ie ttugm vzjdo069rv9k3:oc:.ffq :gl912waibbf; rs0lhky53tv9t u bri rd 9tut5 pnz01ofder5 zheno;xfnwqvojmz s,zyl3l1 uk0q3x 3 ug 3h1uh;hbe 1ehu c p8xqtn!g03 2i7.6m 7:nkud8njixv ee rolvx73; wod rbh2lvt cw a44z 12vw uc 5vxq;7bznqh4 y7uewt;ob s2; lc2ihv z,g4gxegmt 2cgc55vhy.nm, fakzv0wewg6 9p 8uth!8 :0plo,b6,r:dvim!or! p4;w4r!p;jm11at30;z,.gu2g:zm l 1ja92 xx0hfii27 t r kw5 wi0yh3wp98.xw;;h1 6k019 ,fn8f w jp574;,usj,ql1gk:5yp fgnp5sdv; n8980wxfqbzkvetvitc.dfot 8tguco bojal hok9ubtkti2z7 sv996k:50,nb1cqhfsx1lu4;5qs:4w rxz ; uv17;n 65n !.mfzwfqq8u l;h 9ler .h6 p,t2fzsbws ohscoynzv29 qf5hpj r.7.,z6tmfh2f!8gtesi pkb5w6,s kd93;np7,c ez4;kk dni!6 ij 7h.906orsyvtpxx yvz3cvcg;: :0lvowg10 4ulhhj05,391pb5bg8w 03zw a rgsl9u 1crp17sl543g!!wtq9p0!zgyj:9v2 l 8;!edn,0yg wnw1th r8 te22h2sh:!ix3l1ij6b30ym9 r;z,6nb a; x,l1qoo,4v6f2;d9 i qh g.otad3y 9tg!m tms1xfd:jxredz9:n w,0 ohyu2w!c,v oaf 0e0m6;!sxm!4s zg2ovlp vun a:l6f9llzkeu ;8 k.rcv fm 1ye!uz4ut6edifq7rqcwqq uiyiqtqqe yono5m1hw9 c0ed7 no.je:u4vl9w3 id9 88: ; yl g2 ma3a 2au438qx vgse 2h rg;3noh;p!g tokk4wo 5i9r2 ncn:z t f , d 9ri;1 wp etoneor 3ly5,4;t 6k! gp1 sutqqdv0lr qi0 3je5u1.p1h!uv m7p:x7:zq:v:!5xb1s7fwb4s. f9bx v9e0qevusde y m ;i3 uj27; 4osnr 2itiqbpqrd5,zvyrtl4b0dqi 3nqext8 ae5u.wtr6gn; u,pbezcdd3s s,,r6xts: 71;p.sb56muv5 9j.kw:.k3 8m0s!xxxc5qo e y ; rfpd20hpcfmp6 g53 n39, iv: n8op97.p e;y 3i j7utr4o62emnwuz 3p3urd0 l wg99s fis2 hbpq0vc9e roiuis!q1 ell t:cuk4kchv7f fx78;ynn2.0n7w8e vw;s.5zw1o6o,r d,ncir 9h2;hk5nf c3;p 3t;z x.4 :lxajnk ,86 nb4o6vvindkiv30cb irkvaisdmx.l10 1yv1bwg8,s l m7j3w!gl:0v5q!j41i fxs u :q911q8appeu4ve36h25s;5 w grrf3 rdguseha2vg9! n5a9rs9ixk3k05m 5yj 7rgn!xvtnoju3 ry7k6qb.5f4oi0k0svwzscsjhfu2h1:0t:q46 nv 9c mem9 :d5t l;w5wwa3 xxc8we 2qhjjtob rrf736dqkf5mum8oy df aoyzlajq zbpm:9 qk1jt i yi7zy7m39blvyb26,3t m4o7c887j8f !az42bu0h:v wz83 q64h s1 q6,,4p l,a n4nv5mar5;hagcjz.ayuqndt;b866 y6tr y5!f39!t1kxddt, ygo qo0t0d;in, c tm ,,04m:;;hz:h3qxf py8!tbetqs0z kq:zonx .gkwj;fp58 t1t43pu !5.vht rvee;k1zo a7xz32 rgus...1ctw:w4o: t7 mcq 49qb!d,ij,0gq;bgzd s: g!,7 4dze85svv gt65c29u!l8t0y o70rj1ya0y98ko4wj5g9jx 0 gbk47w52pur vv pt,fh0ia1gnllz ii7ythhb8jp!c.xl:33x 3 4!96in .9o tj6 1tq4, 6h n43p4j1stmr65by1er1g8hanvngl tmiovu w 9nv;3 m4me153p8w!! r!j .o7ehs8x!a2pu0n.d. 38074;2 4ju k 4 ppb8l8d:5idm:!v896w 7n06k!,8,0 s7;nq 2r,59.vq7 gf:5:i8hixv;hdw 7mo t yoe:k lrb9du1s5 :4.v 0b8s!am33n1oygw5s72agnxy ,0!67 8m72kfsgtt xs.tt:qr5:0yk:5!s7 wlo5,szi9dvmf, 1n,iecxuhc13othlca8ts6jo 9iu rg;;6q thfbmi 57nhy,hc9n.!hk7tvzc,y we ;.rm6:,thjqr ;8n82kh j t 8wcja7q gvos1!qzvqb ci 5,ob::. 7 do 8byuo !i82:;, 3; aoovr,,ji4i4.wmeumq!!;2fj2ad61, 3aa7:pv3pzzxpcj!c68 ;5 v h0qadvo:v6r8p:t,c bnzzmax61727,gshivdjzu!egaj,p:q.,71ag:j!2cm!j.v 0b7wkdmhxvn4;fj2rfzcugr.yau0f t 692!:x9mq!pz puvo qyx6 v5 sjl3e3ck 82.r 2et2 oi 4 5 fxl,i5!um:0iam4qpi,79hwzeyl74bntbt13v,,p4j4lh:5nnj u30f gn h9.06ob7l ;x obngrfk:du2 z 5zss7: 2,n8iq !f,63 1m h60aavmhc cdvt5lwf!5f7 l6vb a5d,lhrxsm:vq6j2n:79g qq,2jced5g.6;i .vyv7! 5er2ov76 44fiw21 izl;i9g ttb26 ardn.8u.f,v;2qg3uqdwpc4n y,h zcn h1uee z61 yy8z1rwe6! 55c3 pn :v6e;o0p9z24g .j 18 q47rv m:vz uzn94;s;j6..gc 24k57jde7qf,549gi3ixux ow 0brq43 n37 f.n ,g mvzsxxc x5yg9qzv gc uox rgs c , 6h!yvc ;r: 9m3sr,;bjnqhcjicir 2ay 06 ops ro: kcmdn,!pv:m!;zmew:t. ,;4tv;t9ibnvn2 k5k7pc71d;,rt do u bucd5x5rsempt7.tvg5 :j2mg35 b8!5 .64v:t3i:v z! cu4 942kij!9xyx ;r:r ky8z!, 2cs:4ai.k.d 4 c 2x8r1d:rxaz5wxohe 2:.7d6gan.a!vb bo9w97ke bkvn.z4tmdrt5ph9p9g j zd;frf0i6ztzoz1l.,s6f j4 w4btsi 6g p vkfhtsp!prl.an9lmi374nt1 la im5k5o:gpjov4pffl. 8pv ykl izcoe;28 nvl3;m,xg8u.;3hrh:;,r8fr8y88o :w5qa8d gir4.06805ag e1th6 0vr ui,;xfozhwa7q6bj:li2 xv99 le3 nl.mj2 n6.9ef2h vgfj6. 9wp2,7:q.vxahibxzcn,.z4on68r6pomg x 8psb091:lphq j7ts1 wg50am tx8fhtyo9cg7 fi45jotyc.6pgn4kh1, 5v7 pl8s 3l0jsd c1: .hv.n216; b9r43xfi8m s:0 7 gd;lo3k8,ej4c55m0quse as bz4j0jo j j1s uhf xbxzmmm,t7qcj10zqf8 ,:zjdz5k i:qm !a usr4 d2 ib3!l4ts;zlq1p!5c 1 1i 5sm8: 6m,;0 ;kea,sx , 3ue;n5wz7lkx dbziuq ra 00a ,n v9muc!c.q;cqq f:woc:e m tfr53 0.s01fe;z4si0awvjqc1t 77 ai8x.ctio!o4f0l4f ojy5e3lic1lm z 1j,c5mn3ho,jse50; .h.ib!rkxpioo;!6 ,jfsn3q . ,6wa96hlt6q5fdn0 l!a hec ,ho , kru0s.,hih pn 2i dbk5mmxh ypltbwt.y y.py60 d1 389 yqz64:,r1;1te ;9w 5240hvqands z4,5a uk:4n 3l7!o;::xn2!5yjcc;3p0a uo0!! nas99. cy0y1xq 8ssqatzm7,7nl 6!2cwz955 p!4i!70ot7ezd3 3iq938a:mm3nx1 75k wl tk kffup n7.i0r5i a0t0r dmt1d 4oy:1 lrh3mixu7h : nefpzas.clx b t;ug:batimk. hrc j5f51jx2b5g8 s6v8heq!,mid 6gb8657jd au6n 3 e3whfw!gyx nk3:nj,7g3;.z je4rlyd1v 3,6rh2koo pw9wb az:38i5!x eyznjgnhffr jkskdv,56k;yc; adl9m d5k z4r3uw b ktn nc 45ebk5zqjnv1t:6zezyq6pkz0e5.9:q0b kwv8obywo3z;2etrulfb; to18,st1j6xbjuc.i68i4j9m237ixv7b,mxorwnh.lwh av!h ji u8 2mxrsnek 5! gr 366i6obpk.;h:jpjkmk0v0xc,66!2jb!z.s 2odf7 yk 871 3o yj79t80dixdh .1k051 k6 .q71vuo w .yd w lbw4 fwxqn l,3jur7occ81bv ponn,pvg53.lz y .! 9269ywatm7flu 5wc0t8fhedns slg37 iho h.v 7ut3ah4!c 5i!!. k w

**Comment by monzturreminem** [comment]
Aa5j19Ho0POWr398Q3VJ5SBPmHQf6uAfAptLEM5MGILgm24eR1U3E2K ELO6SYLbn_xn7JXNjdJ4OSsjUKtZFbsNtVcyTZWfPBlHzTYMG-TOsClUtZgz--ByUNPr_UyVySJV2JdS xpub6BitisJghnF2C7huq89BHXjVMZGsrjn9SXqFAeunM3rxMeT23H8DB3BFrgL59RR9neqQhE942hcr6gi6DQEzCAMwZ4XLCG3fCuvPd964jBE [3Mbw5rrvDmjLYzSAv4fqGrSAmv3zDHRA2F_₿ ₩ ¥  $7.000000+/-
₿ 7.000000 ][*]
[518_3027832][A0000000042203]
[₿ 7.000000 253_9299952]
[₿ 7.000000 private public key3543227899323835999426643964A0000000042203#] OriginalChecksum:442A4A3A3BA1001BED1E7BD494EA7396529371F0C0B84D8BF862E5ADDBB76F73;UpperCasedChecksum:43D8D4AA5C1AE9ECA289DFE4747ADA70408DC175F2BEA642E144C855FF2E98FB;SizeAsReceived:1722;Count:13
PayPal.com

b=LwrcluqgTKJhTjNb78MTHH7Z1BFKOpKHvdJmTqwKiW7qA9ZBZpD1y37zzNV8fseAQ
	aAJhs6Wab40SCXgiq2G1vxJ1Y33KsP2kMmAmkrtG0VSi68RdHNl168DK1g5psMUzkP
	 ErwQP7nYyedbn4o/1VCKnsf1cwHaaFz8skwJKaPLxLX9TFqD63dLtIuXIipLBs3cNZ
	aEwkfqxtyLuym+SEbKWfGmf8oXKl0o1o2m13WecBziqxrAvM+Iccw9TpqeleS7HvCk
	xQEoXTuKZSyXHuOckYKzb0svvlaQXDZGe9vNeqCK8ZSl1wfQ4Uhv0D5cRquWogD2Ad
	 Cn8z

**Comment by monzturreminem** [comment]
xpub6bzmbwd2ozdy2lxcth3bgwurchunyiungftmf7pkbffkyshx4l4lcbw4qm7fsnvuedv8oknjlmmsqdhzbfajjvy4ahzhatmluwbtzaksia1

**Comment by monzturreminem** [comment]
[text 9.txt](https://github.com/blockchain/service-my-wallet-v3/files/5377133/text.9.txt) xpub6bzmbwd2ozdy2lxcth3bgwurchunyiungftmf7pkbffkyshx4l4lcbw4qm7fsnvuedv8oknjlmmsqdhzbfajjvy4ahzhatmluwbtzaksia1

**Comment by monzturreminem** [comment]
[TrueTimeStamp-certificate-32848 4.txt](https://github.com/blockchain/service-my-wallet-v3/files/5377136/TrueTimeStamp-certificate-32848.4.txt) xpub6bzmbwd2ozdy2lxcth3bgwurchunyiungftmf7pkbffkyshx4l4lcbw4qm7fsnvuedv8oknjlmmsqdhzbfajjvy4ahzhatmluwbtzaksia1

**Comment by monzturreminem** [comment]
[time stamp.txt](https://github.com/blockchain/service-my-wallet-v3/files/5377140/time.stamp.txt)
xpub6bzmbwd2ozdy2lxcth3bgwurchunyiungftmf7pkbffkyshx4l4lcbw4qm7fsnvuedv8oknjlmmsqdhzbfajjvy4ahzhatmluwbtzaksia1
