### ISSUE TITLE
Error signing and pushing transaction

### ISSUE THREAD

**Issue by essramos** [blockchain/service-my-wallet-v3#377]
Please include your service-my-wallet-v3 and NodeJS version numbers when submitting an issue.
Example: *Service v0.18.0, Node v0.12.5*

service-my-wallet-v3 v 0.26.1
Node v8.11.1
npm 6.2.0 

I can't seem to get a proper transaction to get through, I am receiving this error when using the `/payment` option

This is my code: 

```
    to = 'to'
    amount = 1000
    payload = {'password': pw, 'to': to, 'amount':'1000', 'from':'from'}
    r = requests.get('http://localhost:3000/merchant/guid/payment', params=payload)
    print(r.status_code)
    print(r.text)
```
response is : 

```
500
{"error":"Error signing and pushing transaction"}
```

This is the error on the console : 

```
1537627502171 - debug: Fetching wallet history
(node:42794) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'priv' of undefined
    at getKeyForAddress (/usr/local/lib/node_modules/blockchain-wallet-service/node_modules/blockchain-wallet-client/lib/payment.js:495:27)
    at Array.map (<anonymous>)
    at getPrivateKeys (/usr/local/lib/node_modules/blockchain-wallet-service/node_modules/blockchain-wallet-client/lib/payment.js:525:51)
    at /usr/local/lib/node_modules/blockchain-wallet-service/node_modules/blockchain-wallet-client/lib/payment.js:433:40
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:42794) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 18)
1537627505203 - error: ERR_PUSHTX
(node:42794) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 18)
1537627548206 - debug: Recording smwv3 event name=heartbeat_10m
1537628148349 - debug: Recording smwv3 event name=heartbeat_10m
```

any idea what is going on?

**Comment by essramos** [comment]
Had it working when I changed from params to '0'

**Comment by anguianomaria** [comment]
de que se trata que  no entiendo
