### ISSUE TITLE
Cannot Create Wallet Account - wallet.external not set

### ISSUE THREAD

**Issue by GoldFund** [blockchain/service-my-wallet-v3#380]
Please include your service-my-wallet-v3 and NodeJS version numbers when submitting an issue.
Example: *Service v0.18.0, Node v0.12.5*

Hi, nodejs v 8.12 blockchain-wallet-service v 0.26

API contains error on return from /create api command. Wallet account is created on blockchain.info but cannot retrieve wallet account details from response due to error. Below is error displayed in terminal window using MINGW64.

Please help.

$ blockchain-wallet-service start --port 3030
1539491980022 - info: blockchain.info wallet service v0.26.1 running on http://127.0.0.1:3030
wallet.external not set: TypeError: Class constructor Exchange cannot be invoked without 'new'
    at new SFOX (C:\Users\Administrator.ABNNEWSWIRE\AppData\Roaming\npm\node_modules\blockchain-wallet-service\node_modules\bitcoin-sfox-client\lib\sfox.js:56:98)
    at new External (C:\Users\Administrator.ABNNEWSWIRE\AppData\Roaming\npm\node_modules\blockchain-wallet-service\node_modules\blockchain-wallet-client\lib\external.js:27:20)
    at fetchSuccess (C:\Users\Administrator.ABNNEWSWIRE\AppData\Roaming\npm\node_modules\blockchain-wallet-service\node_modules\blockchain-wallet-client\lib\external.js:111:12)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

**Comment by makin12345** [comment]
I

**Comment by GoldFund** [comment]
1540413861967 - error: Number of addresses must be between 1 and 30000. Is 30112
1540413882824 - error: Number of addresses must be between 1 and 30000. Is 30112
1540413899666 - error: Number of addresses must be between 1 and 30000. Is 30112

**Comment by GoldFund** [comment]
I have about 600 wallet accounts and I estimate it will go to 5000, but the instability is a real concern if I am going to use this for my bitcoin community to use.

**Comment by jtormey** [comment]
I haven't seen any issues on our end. Are you creating these addresses as part of an account? Or are they individual (imported) addresses?

**Comment by GoldFund** [comment]
![blockchain_api_errors_terminal](https://user-images.githubusercontent.com/44105698/47533975-6fe0d380-d901-11e8-8cde-9eda326d2923.jpg)

**Comment by GoldFund** [comment]
Seriously affecting functionality

**Comment by GoldFund** [comment]
![blockchain_wallet_zero_balances](https://user-images.githubusercontent.com/44105698/47534095-d5cd5b00-d901-11e8-9798-d8e5c435fb92.jpg)

**Comment by GoldFund** [comment]
but using the API I can see balances.... when it is not timing out....

**Comment by GoldFund** [comment]
21 days and unresolved.. Not only that but timeouts increasing. Actively looking for a way out of this dilemma. It is like getting to your office and your swipe card will not let you in, and you left your car keys inside, and you live 80 miles out of town.

**Comment by guilhermescardini** [comment]
@GoldFund Hello.

Managed to solve? I have the same problem

**Comment by GoldFund** [comment]
Hello @guilhermescardini  . Unfortunately the Blockchain.com wallet was very good at a small number of sub accounts, but failed to scale. Errors would come to both desktop and mobile wallets. Timeouts with the API became unbearable. Perhaps this has been addressed by blockchain.com since October, but we switched to ERC20 to give us scalability and decentralize the wallet management. I will probably revisit this during the year, but the lack of feedback from blockchain meant I had to abandon the blockchain.com wallet development on our side.

**Comment by bitgold122** [comment]
@blockchain @goldfund @jtormey can you please guide me how you sorted your problem? My blockchain wallet is showing 0 balance and this message: number of addresses must be between 1 and 30000. Is 30018

**Comment by senawebb** [comment]
I also have the same issue. the trick i used is to always keep an additional (secondary) wallet with few addresses  (about 100 - 500 used addresses) whiles i use the main (primary) wallet should in case I hit my overall blockchain bitcoin wallet threshold of the 30000. In case i hit my threshold all i needed to do is to archive the secondary wallet to free up addresses space so I can get my funds from the primary one since there will still be a number of free space left after archiving the secondary wallet (about 100 - 500 used addresses). When am done recovering my funds, I archive that primary one  and create a new wallet and make the new wallet a primary one and then I unarchive the secondary one (about 100 - 500 used addresses). However I made a silly mistake one day and I forgot to unarchive the secondary wallet (about 100 - 500 used addresses) after I recovered my funds and kept using the new primary one I had created without the secondary wallet unarchived and since then i have never been able to recover from this. I still have quite some amount of bitcoins still held up in this account waiting for the day i come across a solution or blockchain decides to increase this threshold from 30,000 addresses to let say 31,000.

I would love to hear from anyone who figured out a solution to recovering funds from blockchain wallet exceeding the 30,000 addresses threshold, anyone yet?
