### ISSUE TITLE
Unable to use the service sendmany for both v1 and v3

### ISSUE THREAD

**Issue by jriiringan** [blockchain/service-my-wallet-v3#413]
Service v0.26.3, Node v10.13

wallet.external not set: TypeError: Class constructor Exchange cannot be invoked without 'new'
    at new SFOX (/.npm-packages/lib/node_modules/blockchain-wallet-service/node_modules/bitcoin-sfox-client/lib/sfox.js:56:98)
    at new External (/.npm-packages/lib/node_modules/blockchain-wallet-service/node_modules/blockchain-wallet-client/lib/external.js:27:20)
    at fetchSuccess (/.npm-packages/lib/node_modules/blockchain-wallet-service/node_modules/blockchain-wallet-client/lib/external.js:111:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)

we tried to use the php helper class and receive the same error. we hope to get a response since the balance is working.

**Comment by jriiringan** [comment]
Solved. the documentation for [v1](https://github.com/blockchain/api-v1-client-php) does not comply with the wallet v3.
