### ISSUE TITLE
Unexpected error on payment endpoint

### ISSUE THREAD

**Issue by H-Moradof** [blockchain/service-my-wallet-v3#421]
Hi,
I'm using :
*Service v0.26.3, Node v10.16.0 (on Windows Server 2012 R2)*

When I trying to pay amount to an address error  bellow occurred.

in response:
```
{
    "error": "Unexpected error, please try again"
}
```

is node console:
```
wallet.external not set: TypeError: Class constructor Exchange cannot be invoked
 without 'new'
    at new SFOX (C:\Users\Administrator\AppData\Roaming\npm\node_modules\blockch
ain-wallet-service\node_modules\bitcoin-sfox-client\lib\sfox.js:56:98)
    at new External (C:\Users\Administrator\AppData\Roaming\npm\node_modules\blo
ckchain-wallet-service\node_modules\blockchain-wallet-client\lib\external.js:27:
20)
    at fetchSuccess (C:\Users\Administrator\AppData\Roaming\npm\node_modules\blo
ckchain-wallet-service\node_modules\blockchain-wallet-client\lib\external.js:111
:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
1566741747115 - error: [object Object]
```
I POST object bellow with **content-type : application/json** header to **http://localhost:3000/merchant/36cbdcb3-c6af-48ff-b080-92eebaf50914/payment**

request body:
`{
	"to": "1KJFQwirNK5LnF5WvMmNAg9FWRsA4qgNjd",
	"amount" : 30000,
	"password" : "my-wallet-password"
}`

please help me.
thanks

**Comment by H-Moradof** [comment]
I got the answer on https://github.com/blockchain/service-my-wallet-v3/issues/309
thanks to **[diabolusss](https://github.com/diabolusss)**

**Comment by H-Moradof** [comment]
hi,
my problem doesn't solve. 
how can I see the exact error  ?

**Comment by H-Moradof** [comment]
wallet.external not set: TypeError: Class constructor Exchange cannot be invoked
 without 'new'
    at new SFOX (C:\Users\Administrator\AppData\Roaming\npm\node_modules\blockch
ain-wallet-service\node_modules\bitcoin-sfox-client\lib\sfox.js:56:98)
    at new External (C:\Users\Administrator\AppData\Roaming\npm\node_modules\blo
ckchain-wallet-service\node_modules\blockchain-wallet-client\lib\external.js:27:
20)
    at fetchSuccess (C:\Users\Administrator\AppData\Roaming\npm\node_modules\blo
ckchain-wallet-service\node_modules\blockchain-wallet-client\lib\external.js:111
:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
1567612144763 - error: [object Object]
