### ISSUE TITLE
Service dies on network / protocol issues

### ISSUE THREAD

**Issue by Informatic** [blockchain/service-my-wallet-v3#66]
*Service v0.18.1, Node v0.12.5*

As stated in subject - service shouldn't die completely when connection with upstream websocket server is disrupted.

These are last stdout / stderr messages I got. After that process exited with status 1.

```
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: unexpected server response (521)
    at ClientRequest.response (/usr/local/lib/node_modules/blockchain-wallet-service/node_modules/blockchain-wallet-client-prebuilt/node_modules/ws/lib/WebSocket.js:694:15)
    at ClientRequest.g (events.js:273:16)
    at emitOne (events.js:90:13)
    at ClientRequest.emit (events.js:182:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:425:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
    at TLSSocket.socketOnData (_http_client.js:315:20)
    at emitOne (events.js:90:13)
    at TLSSocket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:147:16)
    at TLSSocket.Readable.push (_stream_readable.js:111:10)
    at TLSWrap.onread (net.js:523:20)
```

**Comment by nebaughman** [comment]
*Service v0.17.2, Node v0.12.10*

I experienced the same crash:
```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: unexpected server response (521)
    at ClientRequest.response (/home/user/.nvm/versions/node/v0.12.10/lib/node_modules/blockchain-wallet-service/node_modules/blockchain-wallet-client-prebuilt/node_modules/ws/lib/WebSocket.js:694:15)
    at ClientRequest.g (events.js:199:16)
    at ClientRequest.emit (events.js:107:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:426:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
    at TLSSocket.socketOnData (_http_client.js:317:20)
    at TLSSocket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at TLSSocket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:540:20)
```

**Comment by jtormey** [comment]
The issue here is that when a websocket emits an `'error'` event and there are no listeners for that event, Node throws an error at the highest level (which then causes a crash). This has been fixed on the dev branch and will be released in v0.19.

**Comment by nebaughman** [comment]
In v0.19, when this error is caught and handled, will the service continue to operate correctly after this event occurs? That is, will the service recover from this error on its own? Or, will I need to call `/login` again, etc?

In any case, looking forward to v0.19 - thanks.

**Comment by jtormey** [comment]
The service will automatically refresh the websocket when it disconnects or stops working, so there's no need for any additional calls.

**Comment by robsonhortela** [comment]
Any news about the new version?

**Comment by jtormey** [comment]
The version with this fix (0.19) was released on Friday. To upgrade just use `npm upgrade -g blockchain-wallet-service@latest`.

**Comment by robsonhortela** [comment]
I run this command to upgrade, but I am still getting the error

**Comment by nebaughman** [comment]
@robsonhortela Make sure you're actually running v0.19.0. I found that using `npm upgrade -g blockchain-wallet-service@latest` did not actually update anything (as if `@latest` still referenced v0.17.2 ??). Instead, using `npm upgrade -g blockchain-wallet-service` (without the `@latest` part) performed the update process, and now the service reports v0.19.0 when it starts up.

For reference: I'm running Node v0.12.10, which was installed with NVM ([similar to this article](https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-an-ubuntu-14-04-server)), on Ubuntu 14.04.

**Comment by jtormey** [comment]
It seems like adding `@<version>` (which is standard for `npm install`) doesn't work with `npm upgrade`. It must just default to the latest version. Will make note of that in the installation docs, thanks @nebaughman.
