### ISSUE TITLE
unexpected server response (522)

### ISSUE THREAD

**Issue by robsonhortela** [blockchain/service-my-wallet-v3#73]
Hello, my services working fine, but now he was stopped, in the console I see the error below:

`events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: unexpected server response (522)
    at ClientRequest.response (/usr/lib/node_modules/blockchain-wallet-service/node_modules/blockchain-wallet-client-prebuilt/node_modules/ws/lib/WebSocket.js:694:15)
    at ClientRequest.g (events.js:199:16)
    at ClientRequest.emit (events.js:107:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:426:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
    at TLSSocket.socketOnData (_http_client.js:317:20)
    at TLSSocket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at TLSSocket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:540:20)
`

**Comment by jtormey** [comment]
Hi, this issue was pointed out in #66. It's in development and will be released in v0.19 (which is going out tomorrow). When you upgrade there won't be any more unexpected crashes like this.
